In [ ]:
import pandas as pd
import os

file_paths = ["../2. 실험에 사용된 전체 데이터/OBS_ASOS_DD_20260310193426.csv"]

# List to hold individual DataFrames
dfs = []

# Loop through each file path, read the CSV, and append to the list
for file_path in file_paths:
    try:
        df = pd.read_csv(file_path, encoding='euc-kr') # Assuming 'euc-kr' encoding for Korean data
        dfs.append(df)
    except Exception as e:
        print(f"Error reading {file_path}: {e}")

# Concatenate all DataFrames into a single DataFrame
if dfs:
    combined_df = pd.concat(dfs, ignore_index=True)
    print(f"Successfully combined {len(dfs)} files into a single DataFrame.")
    print("Combined DataFrame head:")
    display(combined_df.head())
    print("Combined DataFrame info:")
    combined_df.info()
else:
    print("No DataFrames were loaded.")

Successfully combined 6 files into a single DataFrame.
Combined DataFrame head:

   지점 지점명          일시  합계 일조시간(hr)
0  90  속초  2015-01-01          8.9
1  90  속초  2015-01-02          7.7
2  90  속초  2015-01-03          8.9
3  90  속초  2015-01-04          8.7
4  90  속초  2015-01-05          3.9

Combined DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 376508 entries, 0 to 376507
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   지점           376508 non-null  int64
 1   지점명          376508 non-null  object
 2   일시           376508 non-null  object
 3   합계 일조시간(hr)  376508 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 11.5+ MB

In [ ]:
combined_df

         지점  지점명          일시  합계 일조시간(hr)
0        90   속초  2015-01-01          8.9
1        90   속초  2015-01-02          7.7
2        90   속초  2015-01-03          8.9
3        90   속초  2015-01-04          8.7
4        90   속초  2015-01-05          3.9
...     ...  ...         ...          ...
376503  296  북부산  2025-11-02          9.1
376504  296  북부산  2025-11-03          5.6
376505  296  북부산  2025-11-04          8.1
376506  296  북부산  2025-11-05          9.2
376507  296  북부산  2025-11-06          9.4

[376508 rows x 4 columns]

In [ ]:
import pandas as pd

file_path = "/content/drive/MyDrive/일조시간관측데이터/META_관측지점정보_20251107162433.csv"

try:
    df = pd.read_csv(file_path, encoding='euc-kr') # Assuming 'euc-kr' encoding for Korean data
    print(f"Successfully loaded {file_path}.")
    print("DataFrame head:")
    display(df.head())
    print("DataFrame info:")
    df.info()
except Exception as e:
    print(f"Error reading {file_path}: {e}")

Successfully loaded /content/drive/MyDrive/일조시간관측데이터/META_관측지점정보_20251107162433.csv.
DataFrame head:

,지점,시작일,종료일,지점명,지점주소,관리관서,위도,경도,노장해발고도(m),기압계(관측장비지상높이(m)),기온계(관측장비지상높이(m)),풍속계(관측장비지상높이(m)),강우계(관측장비지상높이(m))
0,3,1900-01-01,NaN,선봉,NaN,NaN,42.3167,130.4000,3.0,NaN,NaN,NaN,NaN
1,5,1900-01-01,NaN,삼지연,NaN,NaN,41.8167,128.3167,1386.0,NaN,NaN,NaN,NaN
2,8,1900-01-01,NaN,청진,NaN,NaN,41.7833,129.8167,43.0,NaN,NaN,NaN,NaN
3,12,2007-11-30,NaN,안면도(감),충청남도 태안군 안면읍 승언리,NaN,36.5333,126.3167,60.0,NaN,NaN,NaN,NaN
4,13,2012-01-01,NaN,고산센터,NaN,NaN,33.3000,126.1600,71.0,NaN,NaN,NaN,NaN

DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14892 entries, 0 to 14891
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   지점                14892 non-null  int64
 1   시작일               14892 non-null  object
 2   종료일               2207 non-null   object
 3   지점명               14892 non-null  object
 4   지점주소              5131 non-null   object
 5   관리관서              2687 non-null   object
 6   위도                14857 non-null  float64
 7   경도                14857 non-null  float64
 8   노장해발고도(m)         12609 non-null  float64
 9   기압계(관측장비지상높이(m))  146 non-null    float64
 10  기온계(관측장비지상높이(m))  146 non-null    float64
 11  풍속계(관측장비지상높이(m))  200 non-null    float64
 12  강우계(관측장비지상높이(m))  146 non-null    float64
dtypes: float64(7), int64(1), object(5)
memory usage: 1.5+ MB

In [ ]:
df_filtered = df[df['종료일'].isnull()].copy()
print("DataFrame after removing rows with non-null '종료일':")
display(df_filtered.head())
print("Filtered DataFrame info:")
df_filtered.info()

DataFrame after removing rows with non-null '종료일':

,지점,시작일,종료일,지점명,지점주소,관리관서,위도,경도,노장해발고도(m),기압계(관측장비지상높이(m)),기온계(관측장비지상높이(m)),풍속계(관측장비지상높이(m)),강우계(관측장비지상높이(m))
0,3,1900-01-01,NaN,선봉,NaN,NaN,42.3167,130.4000,3.0,NaN,NaN,NaN,NaN
1,5,1900-01-01,NaN,삼지연,NaN,NaN,41.8167,128.3167,1386.0,NaN,NaN,NaN,NaN
2,8,1900-01-01,NaN,청진,NaN,NaN,41.7833,129.8167,43.0,NaN,NaN,NaN,NaN
3,12,2007-11-30,NaN,안면도(감),충청남도 태안군 안면읍 승언리,NaN,36.5333,126.3167,60.0,NaN,NaN,NaN,NaN
4,13,2012-01-01,NaN,고산센터,NaN,NaN,33.3000,126.1600,71.0,NaN,NaN,NaN,NaN

Filtered DataFrame info:
<class 'pandas.core.frame.DataFrame'>
Index: 12685 entries, 0 to 14891
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   지점                12685 non-null  int64
 1   시작일               12685 non-null  object
 2   종료일               0 non-null      object
 3   지점명               12685 non-null  object
 4   지점주소              3036 non-null   object
 5   관리관서              741 non-null    object
 6   위도                12685 non-null  float64
 7   경도                12685 non-null  float64
 8   노장해발고도(m)         10494 non-null  float64
 9   기압계(관측장비지상높이(m))  100 non-null    float64
 10  기온계(관측장비지상높이(m))  100 non-null    float64
 11  풍속계(관측장비지상높이(m))  115 non-null    float64
 12  강우계(관측장비지상높이(m))  100 non-null    float64
dtypes: float64(7), int64(1), object(5)
memory usage: 1.4+ MB

In [ ]:
import pandas as pd

# 1. 메타 데이터(df_filtered)에서 '지점'을 기준으로 중복 제거
# 위도, 경도 정보만 필요하므로 필요한 컬럼만 선택 후 중복을 제거합니다.
# 이 과정은 메타 데이터만 다루므로 원본 데이터의 '일시'는 영향받지 않습니다.
df_meta_unique = df_filtered[['지점', '위도', '경도']].drop_duplicates(subset=['지점'])

# 2. 원본 데이터(combined_df)에 병합 (Left Merge)
combined_df_merged = pd.merge(
    combined_df,      # 기준이 되는 데이터 ('일시' 포함됨)
    df_meta_unique,   # 중복이 제거된 메타 데이터
    on='지점',        # '지점' 컬럼을 기준으로 병합
    how='left'        # combined_df의 모든 데이터를 유지
)

# 3. 결과 확인
print(f"병합 전 combined_df 행 개수: {len(combined_df)}")
print(f"병합 후 combined_df_merged 행 개수: {len(combined_df_merged)}")

# 혹시 모를 병합 후 중복 확인 (선택 사항)
if len(combined_df) != len(combined_df_merged):
    print("경고: 병합 후 행 개수가 일치하지 않습니다. 메타 데이터를 다시 확인해주세요.")
else:
    print("성공: 행 개수 변화 없이 안전하게 병합되었습니다.")

display(combined_df_merged.head())
combined_df_merged.info()

병합 전 combined_df 행 개수: 376508
병합 후 combined_df_merged 행 개수: 376508
성공: 행 개수 변화 없이 안전하게 병합되었습니다.

   지점 지점명          일시  합계 일조시간(hr)       위도        경도
0  90  속초  2015-01-01          8.9  38.2509  128.5647
1  90  속초  2015-01-02          7.7  38.2509  128.5647
2  90  속초  2015-01-03          8.9  38.2509  128.5647
3  90  속초  2015-01-04          8.7  38.2509  128.5647
4  90  속초  2015-01-05          3.9  38.2509  128.5647

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 376508 entries, 0 to 376507
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   지점           376508 non-null  int64
 1   지점명          376508 non-null  object
 2   일시           376508 non-null  object
 3   합계 일조시간(hr)  376508 non-null  float64
 4   위도           376346 non-null  float64
 5   경도           376346 non-null  float64
dtypes: float64(3), int64(1), object(2)
memory usage: 17.2+ MB

In [ ]:
combined_df_merged

         지점  지점명          일시  합계 일조시간(hr)       위도        경도
0        90   속초  2015-01-01          8.9  38.2509  128.5647
1        90   속초  2015-01-02          7.7  38.2509  128.5647
2        90   속초  2015-01-03          8.9  38.2509  128.5647
3        90   속초  2015-01-04          8.7  38.2509  128.5647
4        90   속초  2015-01-05          3.9  38.2509  128.5647
...     ...  ...         ...          ...      ...       ...
376503  296  북부산  2025-11-02          9.1  35.2178  128.9602
376504  296  북부산  2025-11-03          5.6  35.2178  128.9602
376505  296  북부산  2025-11-04          8.1  35.2178  128.9602
376506  296  북부산  2025-11-05          9.2  35.2178  128.9602
376507  296  북부산  2025-11-06          9.4  35.2178  128.9602

[376508 rows x 6 columns]

In [ ]:
print("결측치 확인 (combined_df_merged):")
display(combined_df_merged.isnull().sum())

결측치 확인 (combined_df_merged):

지점               0
지점명              0
일시               0
합계 일조시간(hr)      0
위도             162
경도             162
dtype: int64

In [ ]:
combined_df_merged['위도'] = combined_df_merged['위도'].fillna(35.8782)
combined_df_merged['경도'] = combined_df_merged['경도'].fillna(128.6522)

print("결측값 채운 후 combined_df_merged의 상위 5개 행:")
display(combined_df_merged.head())

print("결측값 채운 후 combined_df_merged의 결측치 확인:")
display(combined_df_merged.isnull().sum())

결측값 채운 후 combined_df_merged의 상위 5개 행:

   지점 지점명          일시  합계 일조시간(hr)       위도        경도
0  90  속초  2015-01-01          8.9  38.2509  128.5647
1  90  속초  2015-01-02          7.7  38.2509  128.5647
2  90  속초  2015-01-03          8.9  38.2509  128.5647
3  90  속초  2015-01-04          8.7  38.2509  128.5647
4  90  속초  2015-01-05          3.9  38.2509  128.5647

결측값 채운 후 combined_df_merged의 결측치 확인:

지점             0
지점명            0
일시             0
합계 일조시간(hr)    0
위도             0
경도             0
dtype: int64

In [ ]:
combined_df_merged

         지점  지점명          일시  합계 일조시간(hr)       위도        경도
0        90   속초  2015-01-01          8.9  38.2509  128.5647
1        90   속초  2015-01-02          7.7  38.2509  128.5647
2        90   속초  2015-01-03          8.9  38.2509  128.5647
3        90   속초  2015-01-04          8.7  38.2509  128.5647
4        90   속초  2015-01-05          3.9  38.2509  128.5647
...     ...  ...         ...          ...      ...       ...
376503  296  북부산  2025-11-02          9.1  35.2178  128.9602
376504  296  북부산  2025-11-03          5.6  35.2178  128.9602
376505  296  북부산  2025-11-04          8.1  35.2178  128.9602
376506  296  북부산  2025-11-05          9.2  35.2178  128.9602
376507  296  북부산  2025-11-06          9.4  35.2178  128.9602

[376508 rows x 6 columns]

In [ ]:
import os

drive_path = '/content/drive/MyDrive'
pickle_file_path = os.path.join(drive_path, '합계_일조시간.pkl')

combined_df_merged.to_pickle(pickle_file_path)
print(f"combined_df_merged DataFrame이 '{pickle_file_path}' 파일로 저장되었습니다.")

combined_df_merged DataFrame이 '/content/drive/MyDrive/합계_일조시간.pkl' 파일로 저장되었습니다.