# 데이터 결합

In [1]:
import pandas as pd
import os

# 프로젝트 기준 경로 설정 (어떤 환경에서든 동작)
BASE_DIR = os.path.dirname(os.path.abspath('__file__'))
DATA_DIR = os.path.join(BASE_DIR, '..', '3. 외부 및 내부 데이터 관련 데이터와 수집 및 가공 코드')

df_X = pd.read_pickle(os.path.join(DATA_DIR, 'df_통합_LIMS_기상정보_일조포함_결합_60일_gzip_X.pkl'), compression='gzip')
df_y = pd.read_pickle(os.path.join(DATA_DIR, 'df_통합_LIMS_기상정보_일조포함_결합_60일_gzip_y.pkl'), compression='gzip')

print("df_X head:")
display(df_X.head())

print("\ndf_y head:")
display(df_y.head())

df_X head:

,INSPCT_PURPS_NAME,INSPCT_KND_NAME,PRDLST_NM,사용주소,SPLORE_STTUS_NAME,ORGPLCE_NATION_CODE,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,...,일조_50,일조_51,일조_52,일조_53,일조_54,일조_55,일조_56,일조_57,일조_58,일조_59
0,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,4.7,7.6,8.9,9.3,8.3,9.2,7.3,9.9,9.9,7.7
1,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,4.7,7.6,8.9,9.3,8.3,9.2,7.3,9.9,9.9,7.7
2,자가품질위탁검사,식품,과자,검사소,실온,NaN,127.100161,37.279721,12.7,20.0,...,9.3,9.4,8.6,9.6,7.4,10.4,10.2,9.6,9.2,8.6
3,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,8.0,5.6,9.7,10.1,10.1,1.4,10.1,6.2,8.5,9.3
4,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,8.0,5.6,9.7,10.1,10.1,1.4,10.1,6.2,8.5,9.3

df_y head:

  JDGMNT_WORD_NAME   결과 결과값
0               적합  불검출   0
1               적합  불검출   0
2               적합  불검출   0
3               적합  불검출   0
4               적합  불검출   0

In [2]:
df_combined = pd.concat([df_X, df_y], axis=1)

print("df_combined head:")
display(df_combined.head())

df_combined head:

,INSPCT_PURPS_NAME,INSPCT_KND_NAME,PRDLST_NM,사용주소,SPLORE_STTUS_NAME,ORGPLCE_NATION_CODE,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,...,일조_53,일조_54,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값
0,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,9.3,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0
1,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,9.3,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0
2,자가품질위탁검사,식품,과자,검사소,실온,NaN,127.100161,37.279721,12.7,20.0,...,9.6,7.4,10.4,10.2,9.6,9.2,8.6,적합,불검출,0
3,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0
4,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0

# 불필요데이터 삭제

In [40]:
# 제거 전 df_combined의 행 수
initial_rows = df_combined.shape[0]

# 'JDGMNT_WORD_NAME' 칼럼에서 '상기실험확인함' 값을 갖는 행을 식별합니다.
mask_to_remove = df_combined['JDGMNT_WORD_NAME'] == '상기실험확인함'

# 마스크를 반전시켜 '상기실험확인함'이 아닌 행만 선택하여 데이터프레임을 업데이트합니다.
df_combined = df_combined[~mask_to_remove]

# 제거 후 df_combined의 행 수
final_rows = df_combined.shape[0]

# 제거된 행의 수 계산
removed_rows_count = initial_rows - final_rows

print(f"총 {removed_rows_count}개의 행이 제거되었습니다.")
print(f"제거 후 df_combined의 새로운 shape: {df_combined.shape}")

print("\ndf_combined head after filtering:")
display(df_combined.head())

총 106004개의 행이 제거되었습니다.
제거 후 df_combined의 새로운 shape: (337820, 671)

df_combined head after filtering:

,INSPCT_PURPS_NAME,INSPCT_KND_NAME,PRDLST_NM,사용주소,SPLORE_STTUS_NAME,ORGPLCE_NATION_CODE,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,...,일조_53,일조_54,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값
0,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,9.3,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0
1,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,9.3,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0
2,자가품질위탁검사,식품,과자,검사소,실온,NaN,127.100161,37.279721,12.7,20.0,...,9.6,7.4,10.4,10.2,9.6,9.2,8.6,적합,불검출,0
3,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0
4,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0

In [41]:
# 제거 전 df_combined의 행 수
initial_rows_before_removal = df_combined.shape[0]

# 'INSPCT_PURPS_NAME' 칼럼에서 '수입검사' 값을 갖는 행을 식별합니다.
mask_remove_inspect_purps_name = df_combined['INSPCT_PURPS_NAME'] == '수입검사'

# 마스크를 반전시켜 '수입검사'가 아닌 행만 선택하여 데이터프레임을 업데이트합니다.
df_combined = df_combined[~mask_remove_inspect_purps_name]

# 제거 후 df_combined의 행 수
final_rows_after_removal = df_combined.shape[0]

# 제거된 행의 수 계산
removed_inspect_purps_name_count = initial_rows_before_removal - final_rows_after_removal

print(f"총 {removed_inspect_purps_name_count}개의 '수입검사' 행이 제거되었습니다.")
print(f"제거 후 df_combined의 새로운 shape: {df_combined.shape}")

print("\ndf_combined head after filtering '수입검사':")
display(df_combined.head())

총 167060개의 '수입검사' 행이 제거되었습니다.
제거 후 df_combined의 새로운 shape: (170760, 671)

df_combined head after filtering '수입검사':

,INSPCT_PURPS_NAME,INSPCT_KND_NAME,PRDLST_NM,사용주소,SPLORE_STTUS_NAME,ORGPLCE_NATION_CODE,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,...,일조_53,일조_54,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값
0,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,9.3,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0
1,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,9.3,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0
2,자가품질위탁검사,식품,과자,검사소,실온,NaN,127.100161,37.279721,12.7,20.0,...,9.6,7.4,10.4,10.2,9.6,9.2,8.6,적합,불검출,0
3,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0
4,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0

In [42]:
print(df_combined['INSPCT_KND_NAME'].value_counts())

INSPCT_KND_NAME
식품     133708
축산물       460
농산물       372
Name: count, dtype: int64

In [43]:
# 제거 전 df_combined의 행 수
initial_rows_before_removal = df_combined.shape[0]

# 'INSPCT_KND_NAME' 칼럼에서 '축산물' 값을 갖는 행을 식별합니다.
mask_remove_chooksanmul = df_combined['INSPCT_KND_NAME'] == '축산물'

# 마스크를 반전시켜 '축산물'이 아닌 행만 선택하여 데이터프레임을 업데이트합니다.
df_combined = df_combined[~mask_remove_chooksanmul]

# 제거 후 df_combined의 행 수
final_rows_after_removal = df_combined.shape[0]

# 제거된 행의 수 계산
removed_chooksanmul_count = initial_rows_before_removal - final_rows_after_removal

print(f"총 {removed_chooksanmul_count}개의 '축산물' 행이 제거되었습니다.")
print(f"제거 후 df_combined의 새로운 shape: {df_combined.shape}")

print("\ndf_combined head after filtering '축산물':")
display(df_combined.head())

총 460개의 '축산물' 행이 제거되었습니다.
제거 후 df_combined의 새로운 shape: (170300, 671)

df_combined head after filtering '축산물':

,INSPCT_PURPS_NAME,INSPCT_KND_NAME,PRDLST_NM,사용주소,SPLORE_STTUS_NAME,ORGPLCE_NATION_CODE,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,...,일조_53,일조_54,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값
0,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,9.3,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0
1,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,9.3,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0
2,자가품질위탁검사,식품,과자,검사소,실온,NaN,127.100161,37.279721,12.7,20.0,...,9.6,7.4,10.4,10.2,9.6,9.2,8.6,적합,불검출,0
3,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0
4,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0

In [44]:
# | (파이프) 기호를 사용하여 '또는' 조건을 표현합니다.
food_additive_rows = df_combined[df_combined['PRDLST_NM'].str.contains('식품첨가물|덱스트린|혼합제제', na=False)]

print("PRDLST_NM 칼럼에 '식품첨가물','덱스트린','혼합제제'가 포함된 데이터 행:")
display(food_additive_rows.head())

PRDLST_NM 칼럼에 '식품첨가물','덱스트린','혼합제제'가 포함된 데이터 행:

,INSPCT_PURPS_NAME,INSPCT_KND_NAME,PRDLST_NM,사용주소,SPLORE_STTUS_NAME,ORGPLCE_NATION_CODE,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,...,일조_53,일조_54,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값
28147,자가품질위탁검사,식품,난소화성말토덱스트린,제조공장,실온,NaN,127.435207,36.707322,19.6,26.9,...,3.3,5.0,9.4,7.6,13.5,13.3,12.9,적합,불검출,0
28148,자가품질위탁검사,식품,난소화성말토덱스트린,제조공장,실온,NaN,127.435207,36.707322,19.6,26.9,...,3.3,5.0,9.4,7.6,13.5,13.3,12.9,적합,불검출,0
76685,자가품질위탁검사,식품,밀전분유래난소화성말토덱스트린,검사소,냉장,NaN,127.105318,37.403580,NaN,NaN,...,8.9,8.1,9.8,9.0,7.8,5.9,0.0,적합,불검출,0
76979,자가품질위탁검사,식품,밀전분유래난소화성말토덱스트린(제2011-6호),검사소,냉장,NaN,127.105318,37.403580,NaN,NaN,...,10.2,9.2,0.0,4.3,10.3,3.1,10.3,적합,불검출,0
76980,자가품질위탁검사,식품,밀전분유래난소화성말토덱스트린(제2011-6호),검사소,냉장,NaN,127.105318,37.403580,NaN,NaN,...,10.2,9.2,0.0,4.3,10.3,3.1,10.3,적합,불검출,0

In [45]:
initial_rows_before_removal = df_combined.shape[0]

mask_remove_food_additives = df_combined['PRDLST_NM'].str.contains('식품첨가물|덱스트린|혼합제제', na=False)
df_combined = df_combined[~mask_remove_food_additives]

final_rows_after_removal = df_combined.shape[0]
removed_food_additives_count = initial_rows_before_removal - final_rows_after_removal

print(f"총 {removed_food_additives_count}개의 '식품첨가물', '덱스트린', '혼합제제' 관련 행이 제거되었습니다.")
print(f"제거 후 df_combined의 새로운 shape: {df_combined.shape}")

print("\ndf_combined head after filtering food additives:")
display(df_combined.head())

총 111개의 '식품첨가물', '덱스트린', '혼합제제' 관련 행이 제거되었습니다.
제거 후 df_combined의 새로운 shape: (170189, 671)

df_combined head after filtering food additives:

,INSPCT_PURPS_NAME,INSPCT_KND_NAME,PRDLST_NM,사용주소,SPLORE_STTUS_NAME,ORGPLCE_NATION_CODE,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,...,일조_53,일조_54,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값
0,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,9.3,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0
1,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,9.3,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0
2,자가품질위탁검사,식품,과자,검사소,실온,NaN,127.100161,37.279721,12.7,20.0,...,9.6,7.4,10.4,10.2,9.6,9.2,8.6,적합,불검출,0
3,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0
4,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0

In [46]:
print(df_combined['JDGMNT_WORD_NAME'].value_counts())

JDGMNT_WORD_NAME
적합     169375
부적합       814
Name: count, dtype: int64

In [47]:
df_combined

,INSPCT_PURPS_NAME,INSPCT_KND_NAME,PRDLST_NM,사용주소,SPLORE_STTUS_NAME,ORGPLCE_NATION_CODE,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,...,일조_53,일조_54,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값
0,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,9.3,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0
1,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,9.3,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0
2,자가품질위탁검사,식품,과자,검사소,실온,NaN,127.100161,37.279721,12.7,20.0,...,9.6,7.4,10.4,10.2,9.6,9.2,8.6,적합,불검출,0
3,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0
4,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443819,압·몰수품검사,식품,압몰수 임의 품목,검사소,실온,NaN,129.073476,35.187325,NaN,NaN,...,2.7,8.3,12.1,0.9,12.2,12.3,3.4,적합,불검출,0
443820,압·몰수품검사,식품,압몰수 임의 품목,검사소,실온,NaN,129.073476,35.187325,NaN,NaN,...,2.7,8.3,12.1,0.9,12.2,12.3,3.4,적합,불검출,0
443821,압·몰수품검사,식품,압몰수 임의 품목,검사소,실온,NaN,129.073476,35.187325,NaN,NaN,...,9.4,9.0,9.8,9.8,9.7,9.7,9.7,적합,불검출,0
443822,압·몰수품검사,식품,압몰수 임의 품목,검사소,실온,NaN,129.073476,35.187325,15.7,17.2,...,11.1,12.1,2.5,11.5,6.3,3.3,0.3,적합,불검출,0
443823,압·몰수품검사,식품,압몰수 임의 품목,검사소,실온,NaN,129.073476,35.187325,15.7,17.2,...,11.1,12.1,2.5,11.5,6.3,3.3,0.3,적합,불검출,0

# 식품유형분류

In [48]:
import pandas as pd

excel_file_path = os.path.join(BASE_DIR, '..', '2. 실험에 사용된 전체 데이터', '식품유형분류_250915_최종.xlsx')
df_food_types = pd.read_excel(excel_file_path)

display(df_food_types)

    PRDLST_NM  1차 식품 분류 (세부)     Unnamed: 2 2차 식품 분류
0          과자              1  과자류, 빵류 또는 떡류     가공식품
1         과자류              1  과자류, 빵류 또는 떡류     가공식품
2          떡류              1  과자류, 빵류 또는 떡류     가공식품
3          빵류              1  과자류, 빵류 또는 떡류     가공식품
4         추잉껌              1  과자류, 빵류 또는 떡류     가공식품
..        ...            ...            ...      ...
509        황기             32           향신식물   식물성 원료
510        회향             32           향신식물   식물성 원료
511     회향(씨)             32           향신식물   식물성 원료
512     회향(잎)             32           향신식물   식물성 원료
513      회화나무             36         기타 식물류   식물성 원료

[514 rows x 4 columns]

In [49]:
df_food_types['Unnamed: 2'] = df_food_types['Unnamed: 2'].replace('기타 식물류','기타식물류')

In [50]:
unique_unnamed_2_count = df_food_types['Unnamed: 2'].nunique()
print(f"'Unnamed: 2' 칼럼의 유니크값 수: {unique_unnamed_2_count}")

'Unnamed: 2' 칼럼의 유니크값 수: 39

In [51]:
print("df_combined 테이블의 PRDLST_NM 칼럼 유니크 값:")
prdlst_nm_unique_values = df_combined['PRDLST_NM'].unique()
print(f"총 개수: {len(prdlst_nm_unique_values)}개")

df_combined 테이블의 PRDLST_NM 칼럼 유니크 값:
총 개수: 749개

In [52]:
df_combined = pd.merge(df_combined, df_food_types[['PRDLST_NM', 'Unnamed: 2']], on='PRDLST_NM', how='left', suffixes=('', '_food_type'))

In [53]:
df_combined

,INSPCT_PURPS_NAME,INSPCT_KND_NAME,PRDLST_NM,사용주소,SPLORE_STTUS_NAME,ORGPLCE_NATION_CODE,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,...,일조_54,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값,Unnamed: 2
0,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류"
1,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류"
2,자가품질위탁검사,식품,과자,검사소,실온,NaN,127.100161,37.279721,12.7,20.0,...,7.4,10.4,10.2,9.6,9.2,8.6,적합,불검출,0,"과자류, 빵류 또는 떡류"
3,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품)
4,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170184,압·몰수품검사,식품,압몰수 임의 품목,검사소,실온,NaN,129.073476,35.187325,NaN,NaN,...,8.3,12.1,0.9,12.2,12.3,3.4,적합,불검출,0,NaN
170185,압·몰수품검사,식품,압몰수 임의 품목,검사소,실온,NaN,129.073476,35.187325,NaN,NaN,...,8.3,12.1,0.9,12.2,12.3,3.4,적합,불검출,0,NaN
170186,압·몰수품검사,식품,압몰수 임의 품목,검사소,실온,NaN,129.073476,35.187325,NaN,NaN,...,9.0,9.8,9.8,9.7,9.7,9.7,적합,불검출,0,NaN
170187,압·몰수품검사,식품,압몰수 임의 품목,검사소,실온,NaN,129.073476,35.187325,15.7,17.2,...,12.1,2.5,11.5,6.3,3.3,0.3,적합,불검출,0,NaN
170188,압·몰수품검사,식품,압몰수 임의 품목,검사소,실온,NaN,129.073476,35.187325,15.7,17.2,...,12.1,2.5,11.5,6.3,3.3,0.3,적합,불검출,0,NaN

In [54]:
# 'Unnamed: 2' 칼럼이 결측인 행들의 'PRDLST_NM' 칼럼 유니크 수
missing_unnamed_2_df = df_combined[df_combined['Unnamed: 2'].isnull()]
unique_prdlst_nm_missing_count = missing_unnamed_2_df['PRDLST_NM'].nunique()
print(f"1. 'Unnamed: 2' 칼럼이 결측인 행들의 'PRDLST_NM' 칼럼 유니크 수: {unique_prdlst_nm_missing_count}")

1. 'Unnamed: 2' 칼럼이 결측인 행들의 'PRDLST_NM' 칼럼 유니크 수: 240

In [55]:
# df_combined 테이블의 PRDLST_NM 칼럼 유니크 수
total_unique_prdlst_nm_count = df_combined['PRDLST_NM'].nunique()
print(f"2. df_combined 테이블의 'PRDLST_NM' 칼럼 유니크 수: {total_unique_prdlst_nm_count}")

2. df_combined 테이블의 'PRDLST_NM' 칼럼 유니크 수: 749

In [56]:
non_missing_unnamed_2_df = df_combined[df_combined['Unnamed: 2'].notna()]
unique_prdlst_nm_count = non_missing_unnamed_2_df['PRDLST_NM'].nunique()
print(f"'Unnamed: 2' 칼럼이 결측이 아닌 행들의 'PRDLST_NM' 칼럼 유니크 수: {unique_prdlst_nm_count}")

'Unnamed: 2' 칼럼이 결측이 아닌 행들의 'PRDLST_NM' 칼럼 유니크 수: 509

In [57]:
unique_unnamed_2_count = df_combined['Unnamed: 2'].nunique()
print(f"'Unnamed: 2' 칼럼의 유니크값 수: {unique_unnamed_2_count}")

'Unnamed: 2' 칼럼의 유니크값 수: 37

# 2차 제미나이 매칭

In [58]:
missing_unnamed_2_prdlst_nm = df_combined[df_combined['Unnamed: 2'].isnull()]['PRDLST_NM'].unique()
print("\n'Unnamed: 2' 칼럼이 결측인 행들의 'PRDLST_NM' 칼럼 유니크 값:")
for item in missing_unnamed_2_prdlst_nm:
    print(item)

'Unnamed: 2' 칼럼이 결측인 행들의 'PRDLST_NM' 칼럼 유니크 값:
폴리덱스트로스
표고버섯균사체(제2010-35호)
기타코코아가공품
국수
파스타류
과자(가열하지 않고 섭취하는 냉동식품)
액젓
알함유가공품
월계수건조
호박씨건조
쑥갓
들깻잎
상추
기타농산물 종자류
기타서류
오미자
서양자초
차즈기(잎)
천마
치자
귀리건조
겨우살이
배초향
약모밀
엄나무
엉겅퀴
국화
두릅
토마토
키위
아스파라거스
참외
산마늘잎
비트
노루궁뎅이버섯
딸기
옥수수냉동
감귤
기타감귤류
마늘종
복분자냉동
연근
만가닥버섯
배
무(뿌리)건조
무청건조
순무
들깨
치커리(잎)
참깨건조
땅콩건조
녹두건조
메밀건조
율무건조
엇갈이배추
콩나물
차즈기(잎)건조
검정콩건조
연
익모초
개다래나무
민들레
쓴박하
산약
목이버섯건조
기타곡류건조
유채
열무
봄동
머위
방풍나물
미나리
갯개미자리
찔레나무
큰조롱
양송이버섯
목이버섯
케일
송이버섯
은행나무
하수오
음나무
비술나무
죽순건조
호박건조
지치
민트
쇠무릅
삼지구엽초
청경채
하수오(덩이뿌리)
밤
고사리
취나물
개똥쑥
홍화씨
모과
능이버섯건조
소심장
소위장
소폐
콜라비
구기자건조
오미자건조
엉겅퀴건조
서양자초(잎)건조
천마건조
작약건조
민트건조
산수유건조
맥문동건조
왜당귀(어린순)
민들레건조
산조인
우슬건조
살구
파파야건조
고구마건조
들깨건조
줄풀
독활
구기자나무
자리공
자운영건조
지황건조
매실
칡
밀건조
무(잎)건조
기타식물건조
우슬(뿌리)
가시연꽃
치자나무
적작약
멜론
감
딸기냉동
잔대
연자육새싹
토란
구절초
진피
단삼
개사철쑥
왕느릅나무
다래
사상자
석창포
고구마줄기
자두
수박
고사리건조
복숭아
표고버섯건조
검정콩생
셀러리
돼지기타부산물
소기타부산물
메추리알
영.유아용곡류조제식
배추김치
피스타치오건조
조건조
작두콩
기타콩류
사용 중인 튀김용 유지
당면
조미건어포류
영？유아용 특수조제식품
벌꿀
채종유(유채유또는카놀라유)
기타주류
멸치
미역건조
오징어
양송이
숙주나물
다시마건조
유탕면류
두유
재래한식간장
절임류
소주
기타김치
건어포류
콩기름(대두유)
재제소금(재제조소금)
백설탕
기타발효음료
소스류
수산물가공품
만두류
건포도건조
돼지고기
소고기
크랜베리건조
소유
소머리
소간
소비장
돼지위장
돼지간
돼지폐
돼지심장
혼합식육추출가공품
기타콩류건조
팥생
수삼
무화과냉동
냉이
야콘
마늘냉동
아로니아건조
동부
폴리코사놀-사탕수수 왁스알코올(제2006-4호)
올리브잎주정추출물(제2014-9호)
밀크씨슬(카르두스 마리아누스) 추출물
종국
과당
빙과
아마
기타설탕
조미액젓
치자황색소
카라멜색소 Ⅳ
구아검
젤라틴
아질산나트륨
향신료올레오레진류
1제식팽창제제
산화전분
D-자일로오스
탄산수소나트륨
기타
기타전분
미강유(현미유)
팜올레인유
명태
새우
압몰수 임의 품목

In [59]:
# 제거 전 df_combined의 행 수
initial_rows_before_removal = df_combined.shape[0]

# 'PRDLST_NM' 칼럼에서 '압몰수 임의 품목' 값을 갖는 행을 식별합니다.
mask_remove_arbitrary_item = df_combined['PRDLST_NM'] == '압몰수 임의 품목'

# 마스크를 반전시켜 '압몰수 임의 품목'이 아닌 행만 선택하여 데이터프레임을 업데이트합니다.
df_combined = df_combined[~mask_remove_arbitrary_item]

# 제거 후 df_combined의 행 수
final_rows_after_removal = df_combined.shape[0]

# 제거된 행의 수 계산
removed_arbitrary_item_count = initial_rows_before_removal - final_rows_after_removal

print(f"총 {removed_arbitrary_item_count}개의 '압몰수 임의 품목' 행이 제거되었습니다.")
print(f"제거 후 df_combined의 새로운 shape: {df_combined.shape}")

print("\ndf_combined head after filtering '압몰수 임의 품목':")
display(df_combined.head())

총 57개의 '압몰수 임의 품목' 행이 제거되었습니다.
제거 후 df_combined의 새로운 shape: (170132, 672)

df_combined head after filtering '압몰수 임의 품목':

,INSPCT_PURPS_NAME,INSPCT_KND_NAME,PRDLST_NM,사용주소,SPLORE_STTUS_NAME,ORGPLCE_NATION_CODE,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,...,일조_54,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값,Unnamed: 2
0,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류"
1,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류"
2,자가품질위탁검사,식품,과자,검사소,실온,NaN,127.100161,37.279721,12.7,20.0,...,7.4,10.4,10.2,9.6,9.2,8.6,적합,불검출,0,"과자류, 빵류 또는 떡류"
3,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품)
4,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품)

In [60]:
total_rows = df_combined.shape[0]
missing_count = df_combined['Unnamed: 2'].isnull().sum()
non_missing_count = total_rows - missing_count

missing_ratio = (missing_count / total_rows) * 100
non_missing_ratio = (non_missing_count / total_rows) * 100

print(f"'Unnamed: 2' 칼럼의 전체 행 수: {total_rows}")
print(f"\n1. 결측 수: {missing_count}개")
print(f"   결측 비율: {missing_ratio:.2f}%")

print(f"\n2. 결측 아닌 수: {non_missing_count}개")
print(f"   결측 아닌 비율: {non_missing_ratio:.2f}%")

'Unnamed: 2' 칼럼의 전체 행 수: 170132

1. 결측 수: 3374개
   결측 비율: 1.98%

2. 결측 아닌 수: 166758개
   결측 아닌 비율: 98.02%

In [61]:
missing_unnamed_2_prdlst_nm = df_combined[df_combined['Unnamed: 2'].isnull()]['PRDLST_NM'].unique()
print("\n'Unnamed: 2' 칼럼이 결측인 행들의 'PRDLST_NM' 칼럼 유니크 값:")
for item in missing_unnamed_2_prdlst_nm:
    print(item)

print(f"\n총 개수: {len(missing_unnamed_2_prdlst_nm)}개")
print(f"유니크 개수: {len(missing_unnamed_2_prdlst_nm)}개")

'Unnamed: 2' 칼럼이 결측인 행들의 'PRDLST_NM' 칼럼 유니크 값:
폴리덱스트로스
표고버섯균사체(제2010-35호)
기타코코아가공품
국수
파스타류
과자(가열하지 않고 섭취하는 냉동식품)
액젓
알함유가공품
월계수건조
호박씨건조
쑥갓
들깻잎
상추
기타농산물 종자류
기타서류
오미자
서양자초
차즈기(잎)
천마
치자
귀리건조
겨우살이
배초향
약모밀
엄나무
엉겅퀴
국화
두릅
토마토
키위
아스파라거스
참외
산마늘잎
비트
노루궁뎅이버섯
딸기
옥수수냉동
감귤
기타감귤류
마늘종
복분자냉동
연근
만가닥버섯
배
무(뿌리)건조
무청건조
순무
들깨
치커리(잎)
참깨건조
땅콩건조
녹두건조
메밀건조
율무건조
엇갈이배추
콩나물
차즈기(잎)건조
검정콩건조
연
익모초
개다래나무
민들레
쓴박하
산약
목이버섯건조
기타곡류건조
유채
열무
봄동
머위
방풍나물
미나리
갯개미자리
찔레나무
큰조롱
양송이버섯
목이버섯
케일
송이버섯
은행나무
하수오
음나무
비술나무
죽순건조
호박건조
지치
민트
쇠무릅
삼지구엽초
청경채
하수오(덩이뿌리)
밤
고사리
취나물
개똥쑥
홍화씨
모과
능이버섯건조
소심장
소위장
소폐
콜라비
구기자건조
오미자건조
엉겅퀴건조
서양자초(잎)건조
천마건조
작약건조
민트건조
산수유건조
맥문동건조
왜당귀(어린순)
민들레건조
산조인
우슬건조
살구
파파야건조
고구마건조
들깨건조
줄풀
독활
구기자나무
자리공
자운영건조
지황건조
매실
칡
밀건조
무(잎)건조
기타식물건조
우슬(뿌리)
가시연꽃
치자나무
적작약
멜론
감
딸기냉동
잔대
연자육새싹
토란
구절초
진피
단삼
개사철쑥
왕느릅나무
다래
사상자
석창포
고구마줄기
자두
수박
고사리건조
복숭아
표고버섯건조
검정콩생
셀러리
돼지기타부산물
소기타부산물
메추리알
영.유아용곡류조제식
배추김치
피스타치오건조
조건조
작두콩
기타콩류
사용 중인 튀김용 유지
당면
조미건어포류
영？유아용 특수조제식품
벌꿀
채종유(유채유또는카놀라유)
기타주류
멸치
미역건조
오징어
양송이
숙주나물
다시마건조
유탕면류
두유
재래한식간장
절임류
소주
기타김치
건어포류
콩기름(대두유)
재제소금(재제조소금)
백설탕
기타발효음료
소스류
수산물가공품
만두류
건포도건조
돼지고기
소고기
크랜베리건조
소유
소머리
소간
소비장
돼지위장
돼지간
돼지폐
돼지심장
혼합식육추출가공품
기타콩류건조
팥생
수삼
무화과냉동
냉이
야콘
마늘냉동
아로니아건조
동부
폴리코사놀-사탕수수 왁스알코올(제2006-4호)
올리브잎주정추출물(제2014-9호)
밀크씨슬(카르두스 마리아누스) 추출물
종국
과당
빙과
아마
기타설탕
조미액젓
치자황색소
카라멜색소 Ⅳ
구아검
젤라틴
아질산나트륨
향신료올레오레진류
1제식팽창제제
산화전분
D-자일로오스
탄산수소나트륨
기타
기타전분
미강유(현미유)
팜올레인유
명태
새우

총 개수: 239개
유니크 개수: 239개

In [62]:
import pandas as pd

# 1. 엑셀 기준을 적용한 새로운 분류 매핑 데이터 정의
# 누락된 '맥문동건조', '영？유아용 특수조제식품' 포함 및 '특수의료용도식품' 카테고리 신설
# 총 239개 품목
new_classification_map = {
    "농산가공식품류": [
        "귀리건조", "기타곡류건조", "메밀건조", "밀건조", "율무건조", "조건조", # 곡류 건조
        "고구마건조", "무(뿌리)건조", "무(잎)건조", "무청건조", # 서류/채소류 건조
        "검정콩건조", "녹두건조", "기타콩류건조", # 두류 건조
        "땅콩건조", "들깨건조", "참깨건조", "호박씨건조", # 견과류 건조
        "건포도건조", "크랜베리건조", "파파야건조", "아로니아건조", "구기자건조", "산수유건조", "오미자건조", # 과일류 건조
        "죽순건조", "호박건조", "고사리건조", "맥문동건조", # 채소류/기타식물 건조 (맥문동건조 추가됨)
        "능이버섯건조", "목이버섯건조", "표고버섯건조", # 버섯류 건조
        "민트건조", "월계수건조", "차즈기(잎)건조", "민들레건조", "서양자초(잎)건조", "엉겅퀴건조", "우슬건조", "작약건조", "지황건조", "천마건조", "기타식물건조" # 향신/식물류 건조
    ],
    "곡류": ["옥수수냉동"],
    "서류": ["기타서류", "야콘", "토란"],
    "두류": ["검정콩생", "기타콩류", "동부", "작두콩", "팥생"],
    "견과 종실류": ["기타농산물 종자류", "들깨", "밤", "아마", "연자육새싹", "은행나무", "피스타치오건조", "홍화씨"],
    "과일류": ["감", "감귤", "기타감귤류", "다래", "딸기", "딸기냉동", "매실", "멜론", "모과", "무화과냉동", "배", "복분자냉동", "복숭아", "살구", "수박", "오미자", "자두", "참외", "키위"],
    "채소류": ["갯개미자리", "고구마줄기", "고사리", "냉이", "두릅", "들깻잎", "마늘냉동", "마늘종", "머위", "미나리", "방풍나물", "봄동", "비트", "산마늘잎", "상추", "셀러리", "순무", "숙주나물", "쑥갓", "아스파라거스", "엇갈이배추", "연근", "열무", "유채", "청경채", "취나물", "치커리(잎)", "케일", "콜라비", "콩나물", "토마토"],
    "버섯류": ["노루궁뎅이버섯", "만가닥버섯", "목이버섯", "송이버섯", "양송이", "양송이버섯"],
    "향신식물": [
        "민트", "배초향", "쓴박하", "차즈기(잎)",
        "칡", "우슬(뿌리)", "쇠무릅", "적작약", "단삼", "독활", "산약", "산조인", "석창포", "익모초", "잔대", "지치", "하수오", "하수오(덩이뿌리)", "천마", "삼지구엽초", "엉겅퀴", "약모밀", "개똥쑥", "사상자", "민들레", "서양자초", "수삼"
    ],
    "기타 식물류": [
        "가시연꽃","개사철쑥", "개다래나무", "겨우살이", "구기자나무", "구절초", "국화", "비술나무", "엄나무", "연", "왕느릅나무", "음나무", "자리공", "자운영건조", "줄풀", "진피", "찔레나무", "치자", "치자나무", "큰조롱", "왜당귀(어린순)"
    ],
    "조류": ["다시마건조", "미역건조"],
    "식육류": ["돼지간", "돼지고기", "돼지기타부산물", "돼지심장", "돼지위장", "돼지폐", "소간", "소고기", "소기타부산물", "소머리", "소비장", "소심장", "소위장", "소폐"],
    "알류": ["메추리알"],
    "어류": ["멸치", "명태"],
    "무척추 동물": ["새우", "오징어"],
    "유가공품류": ["소유"],
    "알가공품류": ["알함유가공품"],
    "식육가공품류 및 포장육": ["혼합식육추출가공품"],
    "수산가공식품류": ["건어포류", "수산물가공품", "조미건어포류"],
    "과자류": ["과자(가열하지 않고 섭취하는 냉동식품)"],
    "빙과류": ["빙과"],
    "코코아가공품류 또는 초콜릿류": ["기타코코아가공품"],
    "면류": ["국수", "당면", "유탕면류", "파스타류"],
    "장류": ["재래한식간장"],
    "조미식품": ["소스류", "액젓", "조미액젓", "재제소금(재제조소금)"],
    "당류": ["과당", "기타설탕", "백설탕", "D-자일로오스"],
    "식용유지류": ["미강유(현미유)", "사용 중인 튀김용 유지", "채종유(유채유또는카놀라유)", "콩기름(대두유)", "팜올레인유"],
    "절임류 또는 조림류": ["기타김치", "배추김치", "절임류"],
    "주류": ["기타주류", "소주"],
    "음료류": ["기타발효음료", "두유"],
    "특수영양식품": ["영.유아용곡류조제식"],
    "특수의료용도식품": ["영？유아용 특수조제식품"], # 추가됨 (엑셀 기준 적용)
    "벌꿀 및 화분가공품류": ["벌꿀"],
    "기능성원료(건강기능식품 공전 수록)": ["밀크씨슬(카르두스 마리아누스) 추출물", "올리브잎주정추출물(제2014-9호)", "폴리코사놀-사탕수수 왁스알코올(제2006-4호)", "표고버섯균사체(제2010-35호)"],
    "식품첨가물": ["1제식팽창제제", "구아검", "기타전분", "산화전분", "아질산나트륨", "젤라틴", "종국", "치자황색소", "카라멜색소 Ⅳ", "탄산수소나트륨", "폴리덱스트로스", "향신료올레오레진류"],
    "즉석식품류": ["만두류"],
    "기타식품류": ["기타"]
}

# 2. 딕셔너리를 데이터 프레임으로 변환
rows = []
for category, items in new_classification_map.items():
    for item in items:
        rows.append({"PRDLST_NM": item, "분류": category})

df_new_classified = pd.DataFrame(rows)

In [63]:
df_new_classified

     PRDLST_NM       분류
0         귀리건조  농산가공식품류
1       기타곡류건조  농산가공식품류
2         메밀건조  농산가공식품류
3          밀건조  농산가공식품류
4         율무건조  농산가공식품류
..         ...      ...
234    탄산수소나트륨    식품첨가물
235    폴리덱스트로스    식품첨가물
236  향신료올레오레진류    식품첨가물
237        만두류    즉석식품류
238         기타    기타식품류

[239 rows x 2 columns]

In [64]:
new_classification_mapping = df_new_classified.set_index('PRDLST_NM')['분류']



# 'Unnamed: 2' 칼럼에 결측값이 있는 행에 대해서만 PRDLST_NM을 기준으로 '분류' 정보를 매핑합니다.

# 기존에 값이 있는 경우에는 유지됩니다.

df_combined['Unnamed: 2'] = df_combined['Unnamed: 2'].fillna(df_combined['PRDLST_NM'].map(new_classification_mapping))



# 업데이트 후 'Unnamed: 2' 칼럼의 결측값 수 확인

missing_after_update_count = df_combined['Unnamed: 2'].isnull().sum()

print(f"업데이트 후 'Unnamed: 2' 칼럼의 남은 결측값 수: {missing_after_update_count}개")



print("\ndf_combined head after updating 'Unnamed: 2':")

display(df_combined.head())

업데이트 후 'Unnamed: 2' 칼럼의 남은 결측값 수: 0개

df_combined head after updating 'Unnamed: 2':

/tmp/ipython-input-344454949.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_combined['Unnamed: 2'] = df_combined['Unnamed: 2'].fillna(df_combined['PRDLST_NM'].map(new_classification_mapping))

,INSPCT_PURPS_NAME,INSPCT_KND_NAME,PRDLST_NM,사용주소,SPLORE_STTUS_NAME,ORGPLCE_NATION_CODE,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,...,일조_54,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값,Unnamed: 2
0,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류"
1,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류"
2,자가품질위탁검사,식품,과자,검사소,실온,NaN,127.100161,37.279721,12.7,20.0,...,7.4,10.4,10.2,9.6,9.2,8.6,적합,불검출,0,"과자류, 빵류 또는 떡류"
3,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품)
4,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품)

In [65]:
unique_prdlst_nm_count = df_combined['PRDLST_NM'].nunique()
print(f"'PRDLST_NM' 칼럼의 유니크값 수: {unique_prdlst_nm_count}")

'PRDLST_NM' 칼럼의 유니크값 수: 748

In [66]:
unique_unnamed_2_count = df_combined['Unnamed: 2'].nunique()
print(f"'Unnamed: 2' 칼럼의 유니크값 수: {unique_unnamed_2_count}")

'Unnamed: 2' 칼럼의 유니크값 수: 44

In [67]:
df_combined

,INSPCT_PURPS_NAME,INSPCT_KND_NAME,PRDLST_NM,사용주소,SPLORE_STTUS_NAME,ORGPLCE_NATION_CODE,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,...,일조_54,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값,Unnamed: 2
0,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류"
1,자가품질위탁검사,NaN,과자,제조공장,냉동,NaN,127.169855,37.436716,12.1,18.2,...,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류"
2,자가품질위탁검사,식품,과자,검사소,실온,NaN,127.100161,37.279721,12.7,20.0,...,7.4,10.4,10.2,9.6,9.2,8.6,적합,불검출,0,"과자류, 빵류 또는 떡류"
3,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품)
4,자가품질위탁검사,식품,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,실온,NaN,126.770236,37.167154,12.5,20.8,...,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170127,검사명령검사,식품,땅콩버터,검사소,NaN,미국,127.043292,37.467484,-2.1,8.1,...,6.7,8.8,8.7,8.8,8.6,8.5,적합,수치,1.39,농산가공식품류
170162,압·몰수품검사,농산물,녹두건조,검사소,NaN,NaN,126.984332,37.424979,25.4,32.5,...,0.0,0.0,2.6,9.9,4.6,8.3,적합,불검출,0,농산가공식품류
170171,압·몰수품검사,식품,된장,검사소,NaN,NaN,129.073476,35.187325,29.7,34.1,...,11.5,6.8,5.2,12.1,12.1,12.1,적합,불검출,0,장류
170172,압·몰수품검사,식품,된장,검사소,NaN,NaN,129.073476,35.187325,29.7,34.1,...,11.5,6.8,5.2,12.1,12.1,12.1,적합,불검출,0,장류
170173,압·몰수품검사,식품,고추건조,검사소,NaN,NaN,129.073476,35.187325,2.8,6.7,...,8.6,1.5,9.5,9.1,2.8,1.3,적합,불검출,0,농산가공식품류

# 기후결측치 처리

In [68]:
import pandas as pd

def summarize_dataframe(df):
    summary = []
    for col in df.columns:
        unique_count = df[col].nunique()
        missing_count = df[col].isnull().sum()
        missing_percentage = (missing_count / len(df)) * 100
        data_type = df[col].dtype
        # 최빈값 상위 5개 계산
        top_5_modes = df[col].value_counts().nlargest(5).index.tolist()
        summary.append({
            'Column': col,
            'Unique_Count': unique_count,
            'Missing_Count': missing_count,
            'Missing_Percentage': f'{missing_percentage:.2f}%',
            'Data_Type': data_type,
            'Top_5_Modes': str(top_5_modes) # 리스트를 문자열로 변환하여 저장
        })
    return pd.DataFrame(summary)

df_summary = summarize_dataframe(df_combined.iloc[:, :10]) # 첫 10개 칼럼에 대해 요약
print("df_combined 칼럼별 요약 정보 (첫 10개 칼럼):")
display(df_summary)

df_combined 칼럼별 요약 정보 (첫 10개 칼럼):

,Column,Unique_Count,Missing_Count,Missing_Percentage,Data_Type,Top_5_Modes
0,INSPCT_PURPS_NAME,9,0,0.00%,object,"['자가품질위탁검사', '수거검사', '기타', '품질검사', '모니터링검사']"
1,INSPCT_KND_NAME,2,36178,21.26%,object,"['식품', '농산물']"
2,PRDLST_NM,748,0,0.00%,object,"['땅콩 또는 견과류가공품', '과자', '땅콩 또는 견과류 가공품', '캔디류',..."
3,사용주소,2,0,0.00%,object,"['제조공장', '검사소']"
4,SPLORE_STTUS_NAME,5,85025,49.98%,object,"['실온', '냉동', '냉장', '완제품', '소분']"
5,ORGPLCE_NATION_CODE,108,167655,98.54%,object,"['중국', '말레이시아', '베트남', '미국', '대한민국']"
6,x_coord,5522,0,0.00%,float64,"[127.410895905, 127.04329194, 126.98433164, 12..."
7,y_coord,5522,0,0.00%,float64,"[36.413151613, 37.467483559, 37.424978824, 37...."
8,tmprt_150_59,490,10927,6.42%,float64,"[23.8, 23.4, 22.7, 23.1, 23.7]"
9,tmprt_150Top_59,520,10928,6.42%,float64,"[28.0, 29.9, 25.6, 28.5, 27.9]"

In [69]:
columns_to_drop = ['INSPCT_KND_NAME', 'SPLORE_STTUS_NAME', 'ORGPLCE_NATION_CODE']
df_combined = df_combined.drop(columns=columns_to_drop)

print("Columns dropped. New df_combined head:")
display(df_combined.head())
print(f"New df_combined shape: {df_combined.shape}")

Columns dropped. New df_combined head:

,INSPCT_PURPS_NAME,PRDLST_NM,사용주소,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,tmprt_150Lwet_59,hd_150_59,arvlty_300_59,...,일조_54,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값,Unnamed: 2
0,자가품질위탁검사,과자,제조공장,127.169855,37.436716,12.1,18.2,6.2,76.2,0.4,...,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류"
1,자가품질위탁검사,과자,제조공장,127.169855,37.436716,12.1,18.2,6.2,76.2,0.4,...,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류"
2,자가품질위탁검사,과자,검사소,127.100161,37.279721,12.7,20.0,6.3,75.3,0.6,...,7.4,10.4,10.2,9.6,9.2,8.6,적합,불검출,0,"과자류, 빵류 또는 떡류"
3,자가품질위탁검사,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,126.770236,37.167154,12.5,20.8,5.6,80.8,0.4,...,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품)
4,자가품질위탁검사,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,126.770236,37.167154,12.5,20.8,5.6,80.8,0.4,...,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품)

New df_combined shape: (170132, 669)

In [70]:
missing_percentages = df_combined.isnull().sum() / len(df_combined) * 100
high_missing_columns = missing_percentages[missing_percentages >= 50].index.tolist()

if high_missing_columns:
    for col in high_missing_columns:
        print(f"- {col}: {missing_percentages[col]:.2f}%")

- sunshn_Time_59: 78.53%
- sunshn_Time_58: 78.53%
- sunshn_Time_57: 78.53%
- sunshn_Time_56: 78.53%
- sunshn_Time_55: 78.53%
- sunshn_Time_54: 78.53%
- sunshn_Time_53: 78.53%
- sunshn_Time_52: 78.54%
- sunshn_Time_51: 78.53%
- sunshn_Time_50: 78.53%
- sunshn_Time_49: 78.53%
- sunshn_Time_48: 78.54%
- sunshn_Time_47: 78.54%
- sunshn_Time_46: 78.53%
- sunshn_Time_45: 78.53%
- sunshn_Time_44: 78.54%
- sunshn_Time_43: 78.53%
- sunshn_Time_42: 78.53%
- sunshn_Time_41: 78.54%
- sunshn_Time_40: 78.53%
- sunshn_Time_39: 78.54%
- sunshn_Time_38: 78.53%
- sunshn_Time_37: 78.54%
- sunshn_Time_36: 78.53%
- sunshn_Time_35: 78.53%
- sunshn_Time_34: 78.53%
- sunshn_Time_33: 78.53%
- sunshn_Time_32: 78.53%
- sunshn_Time_31: 78.53%
- sunshn_Time_30: 78.53%
- sunshn_Time_29: 78.53%
- sunshn_Time_28: 78.54%
- sunshn_Time_27: 78.54%
- sunshn_Time_26: 78.54%
- sunshn_Time_25: 78.54%
- sunshn_Time_24: 78.54%
- sunshn_Time_23: 78.54%
- sunshn_Time_22: 78.54%
- sunshn_Time_21: 78.54%
- sunshn_Time_20: 78.54%
- sunshn_Time_19: 78.54%
- sunshn_Time_18: 78.54%
- sunshn_Time_17: 78.54%
- sunshn_Time_16: 78.54%
- sunshn_Time_15: 78.54%
- sunshn_Time_14: 78.53%
- sunshn_Time_13: 78.54%
- sunshn_Time_12: 78.54%
- sunshn_Time_11: 78.54%
- sunshn_Time_10: 78.54%
- sunshn_Time_09: 78.54%
- sunshn_Time_08: 78.53%
- sunshn_Time_07: 78.53%
- sunshn_Time_06: 78.53%
- sunshn_Time_05: 78.53%
- sunshn_Time_04: 78.54%
- sunshn_Time_03: 78.53%
- sunshn_Time_02: 78.53%
- sunshn_Time_01: 78.53%
- sunshn_Time_00: 78.53%

In [71]:
df_combined = df_combined.drop(columns=high_missing_columns)

print(f"제거 후 df_combined의 새로운 shape: {df_combined.shape}")
print("제거된 칼럼 목록:")
for col in high_missing_columns:
    print(f"- {col}")

제거 후 df_combined의 새로운 shape: (170132, 609)
제거된 칼럼 목록:
- sunshn_Time_59
- sunshn_Time_58
- sunshn_Time_57
- sunshn_Time_56
- sunshn_Time_55
- sunshn_Time_54
- sunshn_Time_53
- sunshn_Time_52
- sunshn_Time_51
- sunshn_Time_50
- sunshn_Time_49
- sunshn_Time_48
- sunshn_Time_47
- sunshn_Time_46
- sunshn_Time_45
- sunshn_Time_44
- sunshn_Time_43
- sunshn_Time_42
- sunshn_Time_41
- sunshn_Time_40
- sunshn_Time_39
- sunshn_Time_38
- sunshn_Time_37
- sunshn_Time_36
- sunshn_Time_35
- sunshn_Time_34
- sunshn_Time_33
- sunshn_Time_32
- sunshn_Time_31
- sunshn_Time_30
- sunshn_Time_29
- sunshn_Time_28
- sunshn_Time_27
- sunshn_Time_26
- sunshn_Time_25
- sunshn_Time_24
- sunshn_Time_23
- sunshn_Time_22
- sunshn_Time_21
- sunshn_Time_20
- sunshn_Time_19
- sunshn_Time_18
- sunshn_Time_17
- sunshn_Time_16
- sunshn_Time_15
- sunshn_Time_14
- sunshn_Time_13
- sunshn_Time_12
- sunshn_Time_11
- sunshn_Time_10
- sunshn_Time_09
- sunshn_Time_08
- sunshn_Time_07
- sunshn_Time_06
- sunshn_Time_05
- sunshn_Time_04
- sunshn_Time_03
- sunshn_Time_02
- sunshn_Time_01
- sunshn_Time_00

In [72]:
df_combined

,INSPCT_PURPS_NAME,PRDLST_NM,사용주소,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,tmprt_150Lwet_59,hd_150_59,arvlty_300_59,...,일조_54,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값,Unnamed: 2
0,자가품질위탁검사,과자,제조공장,127.169855,37.436716,12.1,18.2,6.2,76.2,0.4,...,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류"
1,자가품질위탁검사,과자,제조공장,127.169855,37.436716,12.1,18.2,6.2,76.2,0.4,...,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류"
2,자가품질위탁검사,과자,검사소,127.100161,37.279721,12.7,20.0,6.3,75.3,0.6,...,7.4,10.4,10.2,9.6,9.2,8.6,적합,불검출,0,"과자류, 빵류 또는 떡류"
3,자가품질위탁검사,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,126.770236,37.167154,12.5,20.8,5.6,80.8,0.4,...,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품)
4,자가품질위탁검사,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,126.770236,37.167154,12.5,20.8,5.6,80.8,0.4,...,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170127,검사명령검사,땅콩버터,검사소,127.043292,37.467484,-2.1,8.1,-9.2,91.3,NaN,...,6.7,8.8,8.7,8.8,8.6,8.5,적합,수치,1.39,농산가공식품류
170162,압·몰수품검사,녹두건조,검사소,126.984332,37.424979,25.4,32.5,21.6,94.2,NaN,...,0.0,0.0,2.6,9.9,4.6,8.3,적합,불검출,0,농산가공식품류
170171,압·몰수품검사,된장,검사소,129.073476,35.187325,29.7,34.1,25.0,92.8,1.5,...,11.5,6.8,5.2,12.1,12.1,12.1,적합,불검출,0,장류
170172,압·몰수품검사,된장,검사소,129.073476,35.187325,29.7,34.1,25.0,92.8,1.5,...,11.5,6.8,5.2,12.1,12.1,12.1,적합,불검출,0,장류
170173,압·몰수품검사,고추건조,검사소,129.073476,35.187325,2.8,6.7,-2.3,81.3,1.2,...,8.6,1.5,9.5,9.1,2.8,1.3,적합,불검출,0,농산가공식품류

In [73]:
import pandas as pd

def summarize_dataframe(df):
    summary = []
    for col in df.columns:
        unique_count = df[col].nunique()
        missing_count = df[col].isnull().sum()
        missing_percentage = (missing_count / len(df)) * 100
        data_type = df[col].dtype
        # 최빈값 상위 5개 계산
        top_5_modes = df[col].value_counts().nlargest(5).index.tolist()
        summary.append({
            'Column': col,
            'Unique_Count': unique_count,
            'Missing_Count': missing_count,
            'Missing_Percentage': f'{missing_percentage:.2f}%',
            'Data_Type': data_type,
            'Top_5_Modes': str(top_5_modes) # 리스트를 문자열로 변환하여 저장
        })
    return pd.DataFrame(summary)

df_summary = summarize_dataframe(df_combined) # 첫 10개 칼럼에 대해 요약

display(df_summary)

,Column,Unique_Count,Missing_Count,Missing_Percentage,Data_Type,Top_5_Modes
0,INSPCT_PURPS_NAME,9,0,0.00%,object,"['자가품질위탁검사', '수거검사', '기타', '품질검사', '모니터링검사']"
1,PRDLST_NM,748,0,0.00%,object,"['땅콩 또는 견과류가공품', '과자', '땅콩 또는 견과류 가공품', '캔디류',..."
2,사용주소,2,0,0.00%,object,"['제조공장', '검사소']"
3,x_coord,5522,0,0.00%,float64,"[127.410895905, 127.04329194, 126.98433164, 12..."
4,y_coord,5522,0,0.00%,float64,"[36.413151613, 37.467483559, 37.424978824, 37...."
...,...,...,...,...,...,...
604,일조_59,141,0,0.00%,float64,"[0.0, 9.2, 9.0, 9.1, 8.7]"
605,JDGMNT_WORD_NAME,2,0,0.00%,object,"['적합', '부적합']"
606,결과,2,0,0.00%,object,"['불검출', '수치']"
607,결과값,2656,0,0.00%,object,"[0, '0.00', '0.0', '0', '0.1']"
608,Unnamed: 2,44,0,0.00%,object,"['농산가공식품류', '과자류, 빵류 또는 떡류', '장류', '조미식품', '건강..."

In [74]:
import re

def fix_nan_auto_group(df):

    '''
    시계열자료 채우기 로직
    '''
    result = df.copy()

    # 컬럼 이름에서 그룹 접두사(e.g., 'wtf', 'vsf')를 자동으로 추출
    # '_01' 과 같은 부분을 제외하고 고유한 그룹 이름을 찾음
    groups = {re.findall(r'(\w+)_', col)[0] for col in df.columns if '_' in col}

    # 각 그룹별로 NaN 값 채우기
    for group_name in groups:
        group_cols = [col for col in df.columns if col.startswith(group_name)]
        # 그룹 내에서 뒤쪽 값으로 먼저 채운 후 앞쪽 값으로 채우기
        result[group_cols] = result[group_cols].bfill(axis=1).ffill(axis=1)

    # 그룹 내에서 채워지지 않은 NaN(행의 양끝)을 0으로 채우기
    result = result.fillna(0)

    return result

In [76]:
df_fixed = fix_nan_auto_group(df_combined)

print("결측치 처리 후 데이터프레임:")
print(df_fixed)

결측치 처리 후 데이터프레임:
       INSPCT_PURPS_NAME                        PRDLST_NM  사용주소     x_coord  \
0               자가품질위탁검사                               과자  제조공장  127.169855
1               자가품질위탁검사                               과자  제조공장  127.169855
2               자가품질위탁검사                               과자   검사소  127.100161
3               자가품질위탁검사  보스웰리아추출물등 복합물(Flexir)(제2021-9호)  제조공장  126.770236
4               자가품질위탁검사  보스웰리아추출물등 복합물(Flexir)(제2021-9호)  제조공장  126.770236
...                  ...                              ...   ...         ...
170127            검사명령검사                             땅콩버터   검사소  127.043292
170162           압·몰수품검사                             녹두건조   검사소  126.984332
170171           압·몰수품검사                               된장   검사소  129.073476
170172           압·몰수품검사                               된장   검사소  129.073476
170173           압·몰수품검사                             고추건조   검사소  129.073476

          y_coord  tmprt_150_59  tmprt_150Top_59  tmprt_150Lwet_59  hd_150_59  \
0       37.436716          12.1             18.2               6.2       76.2
1       37.436716          12.1             18.2               6.2       76.2
2       37.279721          12.7             20.0               6.3       75.3
3       37.167154          12.5             20.8               5.6       80.8
4       37.167154          12.5             20.8               5.6       80.8
...           ...           ...              ...               ...        ...
170127  37.467484          -2.1              8.1              -9.2       91.3
170162  37.424979          25.4             32.5              21.6       94.2
170171  35.187325          29.7             34.1              25.0       92.8
170172  35.187325          29.7             34.1              25.0       92.8
170173  35.187325           2.8              6.7              -2.3       81.3

        arvlty_300_59  ...  일조_54  일조_55  일조_56  일조_57  일조_58  일조_59  \
0                 0.4  ...    8.3    9.2    7.3    9.9    9.9    7.7
1                 0.4  ...    8.3    9.2    7.3    9.9    9.9    7.7
2                 0.6  ...    7.4   10.4   10.2    9.6    9.2    8.6
3                 0.4  ...   10.1    1.4   10.1    6.2    8.5    9.3
4                 0.4  ...   10.1    1.4   10.1    6.2    8.5    9.3
...               ...  ...    ...    ...    ...    ...    ...    ...
170127            0.0  ...    6.7    8.8    8.7    8.8    8.6    8.5
170162            0.0  ...    0.0    0.0    2.6    9.9    4.6    8.3
170171            1.5  ...   11.5    6.8    5.2   12.1   12.1   12.1
170172            1.5  ...   11.5    6.8    5.2   12.1   12.1   12.1
170173            1.2  ...    8.6    1.5    9.5    9.1    2.8    1.3

        JDGMNT_WORD_NAME   결과   결과값     Unnamed: 2
0                     적합  불검출     0  과자류, 빵류 또는 떡류
1                     적합  불검출     0  과자류, 빵류 또는 떡류
2                     적합  불검출     0  과자류, 빵류 또는 떡류
3                     적합  불검출     0     건강기능식품(제품)
4                     적합  불검출     0     건강기능식품(제품)
...                  ...  ...   ...            ...
170127                적합   수치  1.39        농산가공식품류
170162                적합  불검출     0        농산가공식품류
170171                적합  불검출     0             장류
170172                적합  불검출     0             장류
170173                적합  불검출     0        농산가공식품류

[170132 rows x 609 columns]

In [77]:
df_fixed

,INSPCT_PURPS_NAME,PRDLST_NM,사용주소,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,tmprt_150Lwet_59,hd_150_59,arvlty_300_59,...,일조_54,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값,Unnamed: 2
0,자가품질위탁검사,과자,제조공장,127.169855,37.436716,12.1,18.2,6.2,76.2,0.4,...,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류"
1,자가품질위탁검사,과자,제조공장,127.169855,37.436716,12.1,18.2,6.2,76.2,0.4,...,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류"
2,자가품질위탁검사,과자,검사소,127.100161,37.279721,12.7,20.0,6.3,75.3,0.6,...,7.4,10.4,10.2,9.6,9.2,8.6,적합,불검출,0,"과자류, 빵류 또는 떡류"
3,자가품질위탁검사,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,126.770236,37.167154,12.5,20.8,5.6,80.8,0.4,...,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품)
4,자가품질위탁검사,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,126.770236,37.167154,12.5,20.8,5.6,80.8,0.4,...,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170127,검사명령검사,땅콩버터,검사소,127.043292,37.467484,-2.1,8.1,-9.2,91.3,0.0,...,6.7,8.8,8.7,8.8,8.6,8.5,적합,수치,1.39,농산가공식품류
170162,압·몰수품검사,녹두건조,검사소,126.984332,37.424979,25.4,32.5,21.6,94.2,0.0,...,0.0,0.0,2.6,9.9,4.6,8.3,적합,불검출,0,농산가공식품류
170171,압·몰수품검사,된장,검사소,129.073476,35.187325,29.7,34.1,25.0,92.8,1.5,...,11.5,6.8,5.2,12.1,12.1,12.1,적합,불검출,0,장류
170172,압·몰수품검사,된장,검사소,129.073476,35.187325,29.7,34.1,25.0,92.8,1.5,...,11.5,6.8,5.2,12.1,12.1,12.1,적합,불검출,0,장류
170173,압·몰수품검사,고추건조,검사소,129.073476,35.187325,2.8,6.7,-2.3,81.3,1.2,...,8.6,1.5,9.5,9.1,2.8,1.3,적합,불검출,0,농산가공식품류

In [78]:
import pandas as pd

# df_fixed의 결측치 정보를 계산합니다.
missing_data = df_fixed.isnull().sum()

# 결측치가 있는 칼럼들만 필터링합니다.
missing_data = missing_data[missing_data > 0]

if not missing_data.empty:
    print("df_fixed에서 결측치가 있는 칼럼 및 그 비율:")
    for column, count in missing_data.items():
        percentage = (count / len(df_fixed)) * 100
        print(f"- 칼럼: {column}, 결측치 수: {count}, 결측 비율: {percentage:.2f}%")
else:
    print("df_fixed에 결측치가 있는 칼럼이 없습니다.")

df_fixed에 결측치가 있는 칼럼이 없습니다.

################################################################################################

In [79]:
#import pandas as pd

# df_fixed를 피클 파일로 저장 (gzip 압축)
#output_path = os.path.join(BASE_DIR, 'df_fixed.pkl.gz')
#df_fixed.to_pickle(output_path, compression='gzip')

#print(f"df_combined DataFrame이 '{output_path}'에 성공적으로 저장되었습니다.")

# 저장된 피클 파일 경로
#output_path = os.path.join(BASE_DIR, 'df_fixed.pkl.gz')

# DataFrame을 다시 불러옵니다.
#df_fixed = pd.read_pickle(output_path, compression='gzip')
#df_fixed

df_combined DataFrame이 '/content/drive/MyDrive/df_fixed.pkl.gz'에 성공적으로 저장되었습니다.

,INSPCT_PURPS_NAME,PRDLST_NM,사용주소,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,tmprt_150Lwet_59,hd_150_59,arvlty_300_59,...,일조_54,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값,Unnamed: 2
0,자가품질위탁검사,과자,제조공장,127.169855,37.436716,12.1,18.2,6.2,76.2,0.4,...,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류"
1,자가품질위탁검사,과자,제조공장,127.169855,37.436716,12.1,18.2,6.2,76.2,0.4,...,8.3,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류"
2,자가품질위탁검사,과자,검사소,127.100161,37.279721,12.7,20.0,6.3,75.3,0.6,...,7.4,10.4,10.2,9.6,9.2,8.6,적합,불검출,0,"과자류, 빵류 또는 떡류"
3,자가품질위탁검사,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,126.770236,37.167154,12.5,20.8,5.6,80.8,0.4,...,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품)
4,자가품질위탁검사,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,126.770236,37.167154,12.5,20.8,5.6,80.8,0.4,...,10.1,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170127,검사명령검사,땅콩버터,검사소,127.043292,37.467484,-2.1,8.1,-9.2,91.3,0.0,...,6.7,8.8,8.7,8.8,8.6,8.5,적합,수치,1.39,농산가공식품류
170162,압·몰수품검사,녹두건조,검사소,126.984332,37.424979,25.4,32.5,21.6,94.2,0.0,...,0.0,0.0,2.6,9.9,4.6,8.3,적합,불검출,0,농산가공식품류
170171,압·몰수품검사,된장,검사소,129.073476,35.187325,29.7,34.1,25.0,92.8,1.5,...,11.5,6.8,5.2,12.1,12.1,12.1,적합,불검출,0,장류
170172,압·몰수품검사,된장,검사소,129.073476,35.187325,29.7,34.1,25.0,92.8,1.5,...,11.5,6.8,5.2,12.1,12.1,12.1,적합,불검출,0,장류
170173,압·몰수품검사,고추건조,검사소,129.073476,35.187325,2.8,6.7,-2.3,81.3,1.2,...,8.6,1.5,9.5,9.1,2.8,1.3,적합,불검출,0,농산가공식품류

In [83]:
# 'JDGMNT_WORD_NAME' 칼럼을 인코딩하는 맵핑 딕셔너리 생성
encoding_map = {'적합': 0, '부적합': 1}

# 새로운 'JDGMNT_WORD_NAME_encoded' 칼럼 생성
df_fixed['JDGMNT_WORD_NAME_encoded'] = df_fixed['JDGMNT_WORD_NAME'].map(encoding_map)

print("새로운 'JDGMNT_WORD_NAME_encoded' 칼럼이 생성되었습니다. 상위 5개 행을 출력합니다:")
display(df_fixed[['JDGMNT_WORD_NAME', 'JDGMNT_WORD_NAME_encoded']].head())

새로운 'JDGMNT_WORD_NAME_encoded' 칼럼이 생성되었습니다. 상위 5개 행을 출력합니다:

/tmp/ipython-input-3792374782.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_fixed['JDGMNT_WORD_NAME_encoded'] = df_fixed['JDGMNT_WORD_NAME'].map(encoding_map)

  JDGMNT_WORD_NAME  JDGMNT_WORD_NAME_encoded
0               적합                         0
1               적합                         0
2               적합                         0
3               적합                         0
4               적합                         0

In [84]:
df_fixed

,INSPCT_PURPS_NAME,PRDLST_NM,사용주소,x_coord,y_coord,...,JDGMNT_WORD_NAME,결과,결과값,Unnamed: 2,JDGMNT_WORD_NAME_encoded
0,자가품질위탁검사,과자,제조공장,127.169855,37.436716,...,적합,불검출,0,"과자류, 빵류 또는 떡류",0
1,자가품질위탁검사,과자,제조공장,127.169855,37.436716,...,적합,불검출,0,"과자류, 빵류 또는 떡류",0
2,자가품질위탁검사,과자,검사소,127.100161,37.279721,...,적합,불검출,0,"과자류, 빵류 또는 떡류",0
3,자가품질위탁검사,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,126.770236,37.167154,...,적합,불검출,0,건강기능식품(제품),0
4,자가품질위탁검사,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,126.770236,37.167154,...,적합,불검출,0,건강기능식품(제품),0
...,...,...,...,...,...,...,...,...,...,...,...
170127,검사명령검사,땅콩버터,검사소,127.043292,37.467484,...,적합,수치,1.39,농산가공식품류,0
170162,압·몰수품검사,녹두건조,검사소,126.984332,37.424979,...,적합,불검출,0,농산가공식품류,0
170171,압·몰수품검사,된장,검사소,129.073476,35.187325,...,적합,불검출,0,장류,0
170172,압·몰수품검사,된장,검사소,129.073476,35.187325,...,적합,불검출,0,장류,0
170173,압·몰수품검사,고추건조,검사소,129.073476,35.187325,...,적합,불검출,0,농산가공식품류,0

# 다운사이징

In [80]:
# 'JDGMNT_WORD_NAME' 칼럼의 밸류 카운트 계산
value_counts = df_fixed['JDGMNT_WORD_NAME'].value_counts()
display(value_counts)

# 'JDGMNT_WORD_NAME' 칼럼의 비율 계산
percentages = df_fixed['JDGMNT_WORD_NAME'].value_counts(normalize=True) * 100
print("\n'JDGMNT_WORD_NAME' 칼럼의 비율:")
display(percentages)

JDGMNT_WORD_NAME
적합     169323
부적합       809
Name: count, dtype: int64

'JDGMNT_WORD_NAME' 칼럼의 비율:

JDGMNT_WORD_NAME
적합     99.524487
부적합     0.475513
Name: proportion, dtype: float64

In [82]:
unique_inspect_purps_name_count = df_fixed['INSPCT_PURPS_NAME'].nunique()
print(f"'INSPCT_PURPS_NAME' 칼럼의 유니크값 수: {unique_inspect_purps_name_count}")

unique_unnamed_2_count = df_fixed['Unnamed: 2'].nunique()
print(f"'Unnamed: 2' 칼럼의 유니크값 수: {unique_unnamed_2_count}")

'INSPCT_PURPS_NAME' 칼럼의 유니크값 수: 9
'Unnamed: 2' 칼럼의 유니크값 수: 44

In [86]:
data=df_fixed

In [89]:
grouped_data = data.groupby(['INSPCT_PURPS_NAME', 'Unnamed: 2'])['JDGMNT_WORD_NAME_encoded'].mean().reset_index()
filtered_data = grouped_data[grouped_data['JDGMNT_WORD_NAME_encoded'] == 0]
display(filtered_data)

    INSPCT_PURPS_NAME       Unnamed: 2  JDGMNT_WORD_NAME_encoded
0              검사명령검사          농산가공식품류                       0.0
1                  기타       건강기능식품(제품)                       0.0
2                  기타           견과 종실류                       0.0
3                  기타               곡류                       0.0
7                  기타               당류                       0.0
..                ...              ...                       ...
117              품질검사          농산가공식품류                       0.0
118              품질검사               장류                       0.0
119              품질검사             조미식품                       0.0
120              품질검사  코코아가공품류 또는 초콜릿류                       0.0
121  허가.인증 신청 및 신고 검사       건강기능식품(제품)                       0.0

[91 rows x 3 columns]

In [90]:
# 1. 부적합률이 0%인 조합 식별
# JDGMNT_WORD_NAME_encoded의 평균이 0이면, 해당 그룹의 모든 데이터가 0(적합)이라는 의미입니다.
grouped_data = data.groupby(['INSPCT_PURPS_NAME', 'Unnamed: 2'])['JDGMNT_WORD_NAME_encoded'].mean().reset_index()
combinations_to_remove = grouped_data[grouped_data['JDGMNT_WORD_NAME_encoded'] == 0]

# 2. 삭제할 조합의 키 컬럼만 선택
key_columns = ['INSPCT_PURPS_NAME', 'Unnamed: 2']
keys_to_remove = combinations_to_remove[key_columns]

# 삭제 전 행 수 확인 (선택 사항)
print(f"삭제 전 df_fixed 행 수: {len(df_fixed)}")

# 3. df_fixed에서 해당 조합을 가진 행 삭제 (merge & indicator 활용)
# keys_to_remove에 있는 조합과 일치하는 df_fixed의 행을 찾습니다.
merged = df_fixed.merge(keys_to_remove, on=key_columns, how='left', indicator=True)

# '_merge'가 'left_only'인 행(삭제 대상이 아닌 행)만 남깁니다.
df_fixed = merged[merged['_merge'] == 'left_only'].drop(columns=['_merge'])

# 결과 확인
print(f"삭제 후 df_fixed 행 수: {len(df_fixed)}")
display(df_fixed.head())

삭제 전 df_fixed 행 수: 170132
삭제 후 df_fixed 행 수: 158698

,INSPCT_PURPS_NAME,PRDLST_NM,사용주소,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,tmprt_150Lwet_59,hd_150_59,arvlty_300_59,...,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값,Unnamed: 2,JDGMNT_WORD_NAME_encoded
0,자가품질위탁검사,과자,제조공장,127.169855,37.436716,12.1,18.2,6.2,76.2,0.4,...,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류",0
1,자가품질위탁검사,과자,제조공장,127.169855,37.436716,12.1,18.2,6.2,76.2,0.4,...,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류",0
2,자가품질위탁검사,과자,검사소,127.100161,37.279721,12.7,20.0,6.3,75.3,0.6,...,10.4,10.2,9.6,9.2,8.6,적합,불검출,0,"과자류, 빵류 또는 떡류",0
3,자가품질위탁검사,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,126.770236,37.167154,12.5,20.8,5.6,80.8,0.4,...,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품),0
4,자가품질위탁검사,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,126.770236,37.167154,12.5,20.8,5.6,80.8,0.4,...,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품),0

In [92]:
# 'JDGMNT_WORD_NAME' 칼럼의 밸류 카운트 계산
value_counts = df_fixed['JDGMNT_WORD_NAME'].value_counts()
display(value_counts)

# 'JDGMNT_WORD_NAME' 칼럼의 비율 계산
percentages = df_fixed['JDGMNT_WORD_NAME'].value_counts(normalize=True) * 100
print("\n'JDGMNT_WORD_NAME' 칼럼의 비율:")
display(percentages)

JDGMNT_WORD_NAME
적합     157889
부적합       809
Name: count, dtype: int64

'JDGMNT_WORD_NAME' 칼럼의 비율:

JDGMNT_WORD_NAME
적합     99.490227
부적합     0.509773
Name: proportion, dtype: float64

In [93]:
df_fixed

,INSPCT_PURPS_NAME,PRDLST_NM,사용주소,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,tmprt_150Lwet_59,hd_150_59,arvlty_300_59,...,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값,Unnamed: 2,JDGMNT_WORD_NAME_encoded
0,자가품질위탁검사,과자,제조공장,127.169855,37.436716,12.1,18.2,6.2,76.2,0.4,...,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류",0
1,자가품질위탁검사,과자,제조공장,127.169855,37.436716,12.1,18.2,6.2,76.2,0.4,...,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류",0
2,자가품질위탁검사,과자,검사소,127.100161,37.279721,12.7,20.0,6.3,75.3,0.6,...,10.4,10.2,9.6,9.2,8.6,적합,불검출,0,"과자류, 빵류 또는 떡류",0
3,자가품질위탁검사,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,126.770236,37.167154,12.5,20.8,5.6,80.8,0.4,...,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품),0
4,자가품질위탁검사,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,126.770236,37.167154,12.5,20.8,5.6,80.8,0.4,...,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품),0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169957,기타,기타기준규격외,제조공장,128.973543,36.045170,11.2,16.4,7.0,54.2,2.0,...,8.5,8.8,8.7,9.3,9.2,적합,불검출,0,기타식품류,0
169958,기타,기타기준규격외,제조공장,128.973543,36.045170,11.2,16.4,7.0,54.2,2.0,...,8.5,8.8,8.7,9.3,9.2,적합,불검출,0,기타식품류,0
169959,기타,기타기준규격외,제조공장,128.973543,36.045170,11.2,16.4,7.0,54.2,2.0,...,8.5,8.8,8.7,9.3,9.2,적합,불검출,0,기타식품류,0
169960,기타,기타기준규격외,제조공장,127.046083,36.219914,10.4,19.7,1.7,72.0,0.2,...,9.4,6.4,7.0,0.0,8.2,적합,불검출,0,기타식품류,0
169961,기타,기타기준규격외,제조공장,127.046083,36.219914,10.4,19.7,1.7,72.0,0.2,...,9.4,6.4,7.0,0.0,8.2,적합,불검출,0,기타식품류,0

## 깜빡하고 지금 하는 '식품첨가물' 제거

In [96]:
food_additive_rows_in_fixed = df_fixed[df_fixed['Unnamed: 2'].str.contains('식품 첨가물', na=False)]

print("'Unnamed: 2' 칼럼에 '식품첨가물'이 포함된 행:")
display(food_additive_rows_in_fixed)

'Unnamed: 2' 칼럼에 '식품첨가물'이 포함된 행:

Empty DataFrame
Columns: [INSPCT_PURPS_NAME, PRDLST_NM, 사용주소, x_coord, y_coord, tmprt_150_59, tmprt_150Top_59, tmprt_150Lwet_59, hd_150_59, arvlty_300_59, arvlty_300Top_59, afp_59, solrad_Qy_59, soil_Mitr_10_59, tmprt_150_58, tmprt_150Top_58, tmprt_150Lwet_58, hd_150_58, arvlty_300_58, arvlty_300Top_58, afp_58, solrad_Qy_58, soil_Mitr_10_58, tmprt_150_57, tmprt_150Top_57, tmprt_150Lwet_57, hd_150_57, arvlty_300_57, arvlty_300Top_57, afp_57, solrad_Qy_57, soil_Mitr_10_57, tmprt_150_56, tmprt_150Top_56, tmprt_150Lwet_56, hd_150_56, arvlty_300_56, arvlty_300Top_56, afp_56, solrad_Qy_56, soil_Mitr_10_56, tmprt_150_55, tmprt_150Top_55, tmprt_150Lwet_55, hd_150_55, arvlty_300_55, arvlty_300Top_55, afp_55, solrad_Qy_55, soil_Mitr_10_55, tmprt_150_54, tmprt_150Top_54, tmprt_150Lwet_54, hd_150_54, arvlty_300_54, arvlty_300Top_54, afp_54, solrad_Qy_54, soil_Mitr_10_54, tmprt_150_53, tmprt_150Top_53, tmprt_150Lwet_53, hd_150_53, arvlty_300_53, arvlty_300Top_53, afp_53, solrad_Qy_53, soil_Mitr_10_53, tmprt_150_52, tmprt_150Top_52, tmprt_150Lwet_52, hd_150_52, arvlty_300_52, arvlty_300Top_52, afp_52, solrad_Qy_52, soil_Mitr_10_52, tmprt_150_51, tmprt_150Top_51, tmprt_150Lwet_51, hd_150_51, arvlty_300_51, arvlty_300Top_51, afp_51, solrad_Qy_51, soil_Mitr_10_51, tmprt_150_50, tmprt_150Top_50, tmprt_150Lwet_50, hd_150_50, arvlty_300_50, arvlty_300Top_50, afp_50, solrad_Qy_50, soil_Mitr_10_50, tmprt_150_49, tmprt_150Top_49, tmprt_150Lwet_49, hd_150_49, arvlty_300_49, ...]
Index: []

[0 rows x 610 columns]

In [97]:
unique_unnamed_2_values = df_fixed['Unnamed: 2'].unique()
print("'Unnamed: 2' 칼럼의 유니크 값:")
for value in unique_unnamed_2_values:
    print(value)

'Unnamed: 2' 칼럼의 유니크 값:
과자류, 빵류 또는 떡류
건강기능식품(제품)
농산가공식품류
장류
특수영양식품
조미식품
잼류
유가공품류
곡류
두류
채소류
과일류
코코아가공품류 또는 초콜릿류
음료류
기타식품류
식용유지류
식육가공품류 및 포장육
영양성분(건강기능식품 공전 수록)

## 없음

# EDA

In [102]:
# 'Unnamed: 2' 칼럼의 유니크 값별로 전체 건수, 'JDGMNT_WORD_NAME_encoded'가 1인 건수 및 비율 계산
bad_summary_by_unnamed2 = df_fixed.groupby('Unnamed: 2')['JDGMNT_WORD_NAME_encoded'].agg(
    total_count='size',
    부적합_건수='sum',
    부적합_비율='mean'
).reset_index()

print("'Unnamed: 2' 유니크 값 별 전체 건수, '부적합' 건수 및 비율:")
display(bad_summary_by_unnamed2.sort_values(by='부적합_비율', ascending=False))

'Unnamed: 2' 유니크 값 별 전체 건수, '부적합' 건수 및 비율:

            Unnamed: 2  total_count  부적합_건수    부적합_비율
9   영양성분(건강기능식품 공전 수록)            4       2  0.500000
7                식용유지류           21       2  0.095238
13                  잼류           23       2  0.086957
1                   곡류         1877      26  0.013852
12                  장류         9493     128  0.013484
11                 음료류          842       7  0.008314
3        과자류, 빵류 또는 떡류        54684     417  0.007626
15                 채소류          790       6  0.007595
16     코코아가공품류 또는 초콜릿류          312       2  0.006410
14                조미식품         3739      22  0.005884
0           건강기능식품(제품)         2693      15  0.005570
17              특수영양식품          182       1  0.005495
10               유가공품류          784       4  0.005102
6                   두류         1669       6  0.003595
8         식육가공품류 및 포장육          472       1  0.002119
5              농산가공식품류        79232     165  0.002082
2                  과일류          537       1  0.001862
4                기타식품류         1344       2  0.001488

In [105]:
bad_summary_by_unnamed2 = df_fixed.groupby('INSPCT_PURPS_NAME')['JDGMNT_WORD_NAME_encoded'].agg(
    total_count='size',
    부적합_건수='sum',
    부적합_비율='mean'
).reset_index()

display(bad_summary_by_unnamed2.sort_values(by='부적합_비율', ascending=False))

  INSPCT_PURPS_NAME  total_count  부적합_건수    부적합_비율
3  제조.수입품목허가(신고)용검사           99       6  0.060606
0                기타         4148      33  0.007956
1              수거검사        25316     194  0.007663
2          자가품질위탁검사       129135     576  0.004460

In [108]:
df_fixed

,INSPCT_PURPS_NAME,PRDLST_NM,사용주소,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,tmprt_150Lwet_59,hd_150_59,arvlty_300_59,...,일조_55,일조_56,일조_57,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값,Unnamed: 2,JDGMNT_WORD_NAME_encoded
0,자가품질위탁검사,과자,제조공장,127.169855,37.436716,12.1,18.2,6.2,76.2,0.4,...,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류",0
1,자가품질위탁검사,과자,제조공장,127.169855,37.436716,12.1,18.2,6.2,76.2,0.4,...,9.2,7.3,9.9,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류",0
2,자가품질위탁검사,과자,검사소,127.100161,37.279721,12.7,20.0,6.3,75.3,0.6,...,10.4,10.2,9.6,9.2,8.6,적합,불검출,0,"과자류, 빵류 또는 떡류",0
3,자가품질위탁검사,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,126.770236,37.167154,12.5,20.8,5.6,80.8,0.4,...,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품),0
4,자가품질위탁검사,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,126.770236,37.167154,12.5,20.8,5.6,80.8,0.4,...,1.4,10.1,6.2,8.5,9.3,적합,불검출,0,건강기능식품(제품),0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169957,기타,기타기준규격외,제조공장,128.973543,36.045170,11.2,16.4,7.0,54.2,2.0,...,8.5,8.8,8.7,9.3,9.2,적합,불검출,0,기타식품류,0
169958,기타,기타기준규격외,제조공장,128.973543,36.045170,11.2,16.4,7.0,54.2,2.0,...,8.5,8.8,8.7,9.3,9.2,적합,불검출,0,기타식품류,0
169959,기타,기타기준규격외,제조공장,128.973543,36.045170,11.2,16.4,7.0,54.2,2.0,...,8.5,8.8,8.7,9.3,9.2,적합,불검출,0,기타식품류,0
169960,기타,기타기준규격외,제조공장,127.046083,36.219914,10.4,19.7,1.7,72.0,0.2,...,9.4,6.4,7.0,0.0,8.2,적합,불검출,0,기타식품류,0
169961,기타,기타기준규격외,제조공장,127.046083,36.219914,10.4,19.7,1.7,72.0,0.2,...,9.4,6.4,7.0,0.0,8.2,적합,불검출,0,기타식품류,0

In [107]:
import pandas as pd

# df_fixed를 피클 파일로 저장 (gzip 압축)
output_path = os.path.join(BASE_DIR, 'df_fixed.pkl.gz')
df_fixed.to_pickle(output_path, compression='gzip')

print(f"df_combined DataFrame이 '{output_path}'에 성공적으로 저장되었습니다.")

df_combined DataFrame이 '/content/drive/MyDrive/df_fixed.pkl.gz'에 성공적으로 저장되었습니다.