## 영역 M (Modeling) audit 적용 노트북
- 적용 대상 finding: Critical-1, A-M1, B-M3, B-M5, [D-008 fix] SMOTE 제거, 한글 폰트.
- 사용자 결정 외 finding(A-M2/A-M3/A-M4/B-M1/B-M2/B-M4/C-M1, Critical-2/Critical-3)은 코드 수정 없이 보고서 한계점으로 서술한다.
- 본 노트북은 식약처 담당자가 변경 사유를 추적할 수 있도록, 각 핵심 코드 셀 앞에 변경 사유 마크다운을 함께 둔다.

In [1]:
# === [DEFECT-014/015 fix] TF 결정성 환경변수 (반드시 tensorflow import 이전) ===
import os
os.environ['PYTHONHASHSEED'] = '42'
os.environ['TF_DETERMINISTIC_OPS'] = '1'
os.environ['TF_CUDNN_DETERMINISTIC'] = '1'

import pandas as pd

# === 한글 폰트 적용 (영역 M 추가, 영역 E의 font_helper 우선 사용) ===
try:
    from font_helper import setup_korean_font
    setup_korean_font()
except Exception:
    import matplotlib.pyplot as plt
    import platform
    _system = platform.system()
    if _system == 'Windows':
        plt.rcParams['font.family'] = 'Malgun Gothic'
    elif _system == 'Darwin':
        plt.rcParams['font.family'] = 'AppleGothic'
    else:
        plt.rcParams['font.family'] = 'NanumGothic'
    plt.rcParams['axes.unicode_minus'] = False
    print(f"[font] Korean font set inline (system={_system}, font={plt.rcParams['font.family']})")

# 프로젝트 기준 경로 설정
BASE_DIR = os.path.dirname(os.path.abspath('__file__'))

path = os.path.join(BASE_DIR, 'df_enhanced.pkl.gz')
df = pd.read_pickle(path, compression='gzip')

[font_helper] 한글 폰트 적용: NanumGothic (axes.unicode_minus=False)

In [2]:
df['INSPCT_PURPS_NAME'].value_counts().reset_index().rename(columns={'index': 'INSPCT_PURPS_NAME', 'count': '개수'})

  INSPCT_PURPS_NAME     개수
0          자가품질위탁검사  61028
1              수거검사  17198
2                기타   1794
3              품질검사    681
4  제조.수입품목허가(신고)용검사     99
5            모니터링검사     70
6  허가.인증 신청 및 신고 검사      7
7            검사명령검사      3
8           압·몰수품검사      3

In [3]:
df

,INSPCT_PURPS_NAME,PRDLST_NM,사용주소,x_coord,y_coord,tmprt_150_59,tmprt_150Top_59,tmprt_150Lwet_59,hd_150_59,arvlty_300_59,...,일조_58,일조_59,JDGMNT_WORD_NAME,결과,결과값,1차 식품 분류,JDGMNT_WORD_NAME_encoded,독소 생성 최적 온도 일수,저습도 일수,연속 무강수 일수
0,자가품질위탁검사,과자,제조공장,127.169855,37.436716,12.1,18.2,6.2,76.2,0.4,...,9.9,7.7,적합,불검출,0,"과자류, 빵류 또는 떡류",0,0,2,2.0
1,자가품질위탁검사,과자,검사소,127.100161,37.279721,12.7,20.0,6.3,75.3,0.6,...,9.2,8.6,적합,불검출,0,"과자류, 빵류 또는 떡류",0,0,4,1.0
2,자가품질위탁검사,보스웰리아추출물등 복합물(Flexir)(제2021-9호),제조공장,126.770236,37.167154,12.5,20.8,5.6,80.8,0.4,...,8.5,9.3,적합,불검출,0,건강기능식품(제품),0,0,0,7.0
3,자가품질위탁검사,과자,제조공장,126.953385,37.349660,13.9,21.2,8.6,73.7,0.6,...,9.3,9.4,적합,불검출,0,"과자류, 빵류 또는 떡류",0,0,3,3.0
4,자가품질위탁검사,땅콩 또는 견과류가공품,제조공장,127.065021,37.856262,10.6,21.1,2.7,77.4,0.2,...,8.6,8.7,적합,불검출,0,농산가공식품류,0,0,0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80878,검사명령검사,땅콩버터,검사소,127.043292,37.467484,-2.1,8.1,-9.2,91.3,0.0,...,8.6,8.5,적합,수치,2.09,농산가공식품류,0,0,0,3.0
80879,검사명령검사,땅콩버터,검사소,127.043292,37.467484,-2.1,8.1,-9.2,91.3,0.0,...,8.6,8.5,적합,수치,1.39,농산가공식품류,0,0,0,3.0
80880,압·몰수품검사,녹두건조,검사소,126.984332,37.424979,25.4,32.5,21.6,94.2,0.0,...,4.6,8.3,적합,불검출,0,농산가공식품류,0,1,0,7.0
80881,압·몰수품검사,된장,검사소,129.073476,35.187325,29.7,34.1,25.0,92.8,1.5,...,12.1,12.1,적합,불검출,0,장류,0,0,0,1.0
80882,압·몰수품검사,고추건조,검사소,129.073476,35.187325,2.8,6.7,-2.3,81.3,1.2,...,2.8,1.3,적합,불검출,0,농산가공식품류,0,0,4,7.0

In [4]:
print(df['JDGMNT_WORD_NAME_encoded'].value_counts())
print(df['JDGMNT_WORD_NAME_encoded'].value_counts(normalize=True))

JDGMNT_WORD_NAME_encoded
0    80567
1      316
Name: count, dtype: int64
JDGMNT_WORD_NAME_encoded
0    0.996093
1    0.003907
Name: proportion, dtype: float64

In [5]:
df.shape

(80883, 613)

In [6]:
df.columns

Index(['INSPCT_PURPS_NAME', 'PRDLST_NM', '사용주소', 'x_coord', 'y_coord',
       'tmprt_150_59', 'tmprt_150Top_59', 'tmprt_150Lwet_59', 'hd_150_59',
       'arvlty_300_59',
       ...
       '일조_58', '일조_59', 'JDGMNT_WORD_NAME', '결과', '결과값', '1차 식품 분류',
       'JDGMNT_WORD_NAME_encoded', '독소 생성 최적 온도 일수', '저습도 일수', '연속 무강수 일수'],
      dtype='object', length=613)

In [7]:
import pandas as pd
import numpy as np

# 1. 2열: 'Unnamed: 2' 칼럼의 총 개수 계산 (Value Counts)
# groupby().size()는 'Unnamed: 2'를 인덱스로 하는 총 개수 Series를 반환합니다.
total_counts = df.groupby('1차 식품 분류').size().to_frame(name='총 개수')

# 2. 3, 4열: 'JDGMNT_WORD_NAME_encoded' 칼럼의 유니크 값 별 카운트
# pd.crosstab()은 두 칼럼 간의 교차표를 생성합니다.
# 'Unnamed: 2'가 인덱스, 'JDGMNT_WORD_NAME_encoded'의 유니크 값(0, 1)이 칼럼이 됩니다.
cross_table = pd.crosstab(df['1차 식품 분류'], df['JDGMNT_WORD_NAME_encoded'])

# 3. 두 데이터프레임(total_counts, cross_table)을 합칩니다.
# 두 데이터프레임 모두 'Unnamed: 2'를 인덱스로 가지고 있으므로 axis=1로 옆으로 붙입니다.
result_df = pd.concat([total_counts, cross_table], axis=1)

# 4. 1열: 'Unnamed: 2' (인덱스)를 칼럼으로 변환
# reset_index()를 사용하여 인덱스를 첫 번째 칼럼으로 이동시킵니다.
result_df = result_df.reset_index()

In [8]:
result_df

               1차 식품 분류   총 개수      0    1
0            건강기능식품(제품)   1801   1790   11
1                견과 종실류   1029   1029    0
2                    곡류   1182   1173    9
3                   과일류    377    377    0
4                   과자류      1      1    0
5         과자류, 빵류 또는 떡류  24902  24773  129
6   기능성원료(건강기능식품 공전 수록)     97     97    0
7                기타 식물류    109    109    0
8                 기타식물류     89     89    0
9                 기타식품류    798    796    2
10              농산가공식품류  36786  36697   89
11                   당류    151    151    0
12                   두류   1183   1183    0
13            두부류 또는 묵류     30     30    0
14                   면류    180    180    0
15               무척추 동물      5      5    0
16                  버섯류     88     88    0
17          벌꿀 및 화분가공품류      1      1    0
18                  빙과류     43     43    0
19                   서류     98     98    0
20              수산가공식품류    148    148    0
21                식용유지류    301    299    2
22         식육가공품류 및 포장육    189    189    0
23                  식육류     44     44    0
24                식품첨가물     24     24    0
25                알가공품류      5      5    0
26                   알류     27     27    0
27                   어류      6      6    0
28   영양성분(건강기능식품 공전 수록)     83     81    2
29                  우유류     39     39    0
30                유가공품류    540    537    3
31                  음료류    683    680    3
32                   장류   4771   4719   52
33                   잼류     29     27    2
34           절임류 또는 조림류    233    233    0
35                   조류      6      6    0
36                 조미식품   1624   1613   11
37                   주류    102    102    0
38                즉석식품류    227    227    0
39                  채소류    555    554    1
40      코코아가공품류 또는 초콜릿류    373    373    0
41               특수영양식품   1291   1291    0
42             특수의료용도식품     11     11    0
43                 향신식물    622    622    0

In [9]:
value_counts = df['1차 식품 분류'].value_counts()
low_frequency_values = value_counts[value_counts < 100].index
print("Values being replaced with '기타' (frequency < 100):", low_frequency_values.tolist())
df['1차 식품 분류'] = df['1차 식품 분류'].replace(low_frequency_values, '기타')

Values being replaced with '기타' (frequency < 100): ['서류', '기능성원료(건강기능식품 공전 수록)', '기타식물류', '버섯류', '영양성분(건강기능식품 공전 수록)', '식육류', '빙과류', '우유류', '두부류 또는 묵류', '잼류', '알류', '식품첨가물', '특수의료용도식품', '어류', '조류', '알가공품류', '무척추 동물', '과자류', '벌꿀 및 화분가공품류']

In [10]:
df['1차 식품 분류'].value_counts().reset_index().rename(columns={'index': '1차 식품 분류', 'count': '개수'})

           1차 식품 분류     개수
0           농산가공식품류  36786
1     과자류, 빵류 또는 떡류  24902
2                장류   4771
3        건강기능식품(제품)   1801
4              조미식품   1624
5            특수영양식품   1291
6                두류   1183
7                곡류   1182
8            견과 종실류   1029
9             기타식품류    798
10               기타    726
11              음료류    683
12             향신식물    622
13              채소류    555
14            유가공품류    540
15              과일류    377
16  코코아가공품류 또는 초콜릿류    373
17            식용유지류    301
18       절임류 또는 조림류    233
19            즉석식품류    227
20     식육가공품류 및 포장육    189
21               면류    180
22               당류    151
23          수산가공식품류    148
24           기타 식물류    109
25               주류    102

In [11]:
df.columns

Index(['INSPCT_PURPS_NAME', 'PRDLST_NM', '사용주소', 'x_coord', 'y_coord',
       'tmprt_150_59', 'tmprt_150Top_59', 'tmprt_150Lwet_59', 'hd_150_59',
       'arvlty_300_59',
       ...
       '일조_58', '일조_59', 'JDGMNT_WORD_NAME', '결과', '결과값', '1차 식품 분류',
       'JDGMNT_WORD_NAME_encoded', '독소 생성 최적 온도 일수', '저습도 일수', '연속 무강수 일수'],
      dtype='object', length=613)

In [12]:
non_timeseries_cols = ['INSPCT_PURPS_NAME', 'PRDLST_NM', '사용주소', 'x_coord', 'y_coord','JDGMNT_WORD_NAME', '결과', '결과값', '1차 식품 분류',
       'JDGMNT_WORD_NAME_encoded', '독소 생성 최적 온도 일수', '저습도 일수', '연속 무강수 일수'
    ]

In [13]:
# Identify timeseries patterns
all_cols = df.columns.tolist()
timeseries_patterns = []
for col in all_cols:
    # Check if the column is not in non_timeseries_cols and matches a pattern like 'abc_XX'
    if col not in non_timeseries_cols and '_' in col and col.split('_')[-1].isdigit():
        pattern = '_'.join(col.split('_')[:-1])
        if pattern not in timeseries_patterns:
            timeseries_patterns.append(pattern)

print("Identified timeseries patterns:", timeseries_patterns)

Identified timeseries patterns: ['tmprt_150', 'tmprt_150Top', 'tmprt_150Lwet', 'hd_150', 'arvlty_300', 'arvlty_300Top', 'afp', 'solrad_Qy', 'soil_Mitr_10', '일조']

In [14]:
timeseries_patterns

['tmprt_150',
 'tmprt_150Top',
 'tmprt_150Lwet',
 'hd_150',
 'arvlty_300',
 'arvlty_300Top',
 'afp',
 'solrad_Qy',
 'soil_Mitr_10',
 '일조']

## 시계열 timesteps를 50일로 변환

In [15]:
import pandas as pd
import numpy as np

def convert_60days_to_50days(df):
    """
    [DEFECT-009/010/011 fix - Round 1 G3 옵션 D1] 검사일 가까운 50일(_00~_49)만 사용 + time-major 재정렬
      - 작년 과제와 동일하게 검사일(d0)에서 49일 전까지 50일치 시계열만 사용.
      - DEFECT-011 해결: 비균등 timestep grid (np.linspace round) 자체 제거
        -> 균등 1일 간격 50 timestep 유지
      - DEFECT-010 해결: 컬럼명 재부여 안함 -> 원본 `_00~_49` 의 "검사일 d일 전" 의미 보존
      - DEFECT-009 해결: 컬럼 순서를 time-major 로 재정렬
        (day i 의 모든 변수가 인접하도록: afp_00, arvlty_300_00, ..., afp_01, arvlty_300_01, ...)
        -> C-order reshape(-1, 50, n_features) 시 시간축이 실제 시간이 되도록 함
      - `_50~_59` 컬럼은 제외 (작년 50일 baseline 과 일치).
    함수명은 호환성을 위해 유지 (실제 동작은 _00~_49 50일 raw 보존 + time-major 정렬).
    """
    new_data = {}

    # 1. 비시계열 컬럼은 그대로 복사
    for col in non_timeseries_cols:
        if col in df.columns:
            new_data[col] = df[col].values

    # 2. 시계열 컬럼 중 _00~_49 (검사일 가까운 50일) 만 복사
    for pattern in timeseries_patterns:
        for i in range(50):
            col = f'{pattern}_{i:02d}'
            if col in df.columns:
                new_data[col] = df[col].values

    # 새로운 데이터프레임 생성
    df_new = pd.DataFrame(new_data)

    # 3. 컬럼 순서 정렬: time-major (day i 의 모든 변수가 인접)
    # 예: [afp_00, arvlty_300_00, ..., afp_01, arvlty_300_01, ..., afp_49, arvlty_300_49, ...]
    # -> C-order reshape(N, 50, n_features) 시 ts[r, t, :] 가 day t 의 변수들
    timeseries_cols_time_major = [
        f'{p}_{i:02d}'
        for i in range(50)
        for p in timeseries_patterns
        if f'{p}_{i:02d}' in df_new.columns
    ]
    other_cols = [col for col in df_new.columns if col not in timeseries_cols_time_major]

    df_new = df_new[timeseries_cols_time_major + other_cols]

    return df_new


# 사용 예시: 검사일 가까운 50일치 (_00~_49) 만 time-major 로 정렬
df_50days = convert_60days_to_50days(df)
df = df_50days.copy()
n_ts_cols = sum(1 for c in df_50days.columns if any(c.startswith(f'{p}_') for p in timeseries_patterns))
print(f"변환 후 shape: {df_50days.shape}, 시계열컬럼수: {n_ts_cols} (= {n_ts_cols / len(timeseries_patterns):.1f} per pattern)")
print(f"변환 후 columns 처음 20개 (time-major 확인): {df_50days.columns.tolist()[:20]}")

변환 후 shape: (80883, 513), 시계열컬럼수: 500 (= 50.0 per pattern)
변환 후 columns 처음 20개 (time-major 확인): ['tmprt_150_00', 'tmprt_150Top_00', 'tmprt_150Lwet_00', 'hd_150_00', 'arvlty_300_00', 'arvlty_300Top_00', 'afp_00', 'solrad_Qy_00', 'soil_Mitr_10_00', '일조_00', 'tmprt_150_01', 'tmprt_150Top_01', 'tmprt_150Lwet_01', 'hd_150_01', 'arvlty_300_01', 'arvlty_300Top_01', 'afp_01', 'solrad_Qy_01', 'soil_Mitr_10_01', '일조_01']

### [영역 M / Critical-1] Target_Mean 누설 차단
- 기존 코드는 train·test 분리 전에 전체 데이터로 cross_mean을 계산해 라벨 정보가 train fold에 새어들었다.
- 본 셀에서는 fit/transform 함수만 정의하고, 실제 fit은 아래 모델링 셀의 `preprocess()` 안에서 split 이후에만 호출한다.
- 컬럼 'Target_Mean'은 임시 placeholder(전역 평균 상수)로 채워두며, 모델 입력 직전에 train fold 기준 값으로 덮어쓴다.

In [16]:
# --- 영역 M / Critical-1 (Target_Mean 누설 수정) ---
# 기존 코드: 전체 df로 cross_mean을 계산해 train/test 모두에 매핑하면
#           test 라벨 정보가 train fold의 인코딩에 새어든다 (data leakage).
# 수정: cross_mean 계산을 함수화하고 split 이후 train만으로 fit 한다.
#       (실제 fit/transform 호출은 아래 모델링 셀의 preprocess() 함수 내부에서 수행)

df = df.drop(columns=['사용주소', 'PRDLST_NM', 'JDGMNT_WORD_NAME', 'x_coord', 'y_coord'])

# 교차 조합 키만 미리 만들어 둔다 (값 자체는 상수이므로 누설 아님)
df['교차_조합'] = df['1차 식품 분류'] + '_' + df['INSPCT_PURPS_NAME']


def fit_target_mean(df_train, group_col='교차_조합', target_col='JDGMNT_WORD_NAME_encoded', m=20.0):
    """train fold만으로 교차 조합별 Target_Mean을 학습하고 (cross_mean Series, fallback) 반환.

    [DEFECT-020 fix] m-estimate smoothing 적용: (sum + m*prior)/(count + m).
    Micci-Barreca (2001) SIGKDD Explor. 3(1), 27-32. m=20 = sklearn TargetEncoder >=1.3 empirical-Bayes default.
    소표본 group cross_mean ∈ {0, 1} 극단화 → minority 라벨 누설 통로 차단 (0.5% 불균형 안전망).
    """
    grouped = df_train.groupby(group_col)[target_col]
    n_g = grouped.count()
    sum_g = grouped.sum()
    prior = df_train[target_col].mean()  # global mean, 미관측 조합 fallback 도 동일
    cross_mean = (sum_g + m * prior) / (n_g + m)
    fallback = prior
    return cross_mean, fallback


def transform_target_mean(df_in, cross_mean, fallback, group_col='교차_조합'):
    """학습된 cross_mean으로 임의 fold(또는 test)에 매핑. 미관측은 fallback."""
    return df_in[group_col].map(cross_mean).fillna(fallback)


# 호환성을 위해 기존 변수 'Target_Mean' 컬럼을 임시로 채워둔다
# (이후 모델링 셀에서 split 후 train fit -> transform 으로 덮어쓸 것임).
# 임시 값은 전역 평균(상수)이므로 라벨 누설 없음.
df['Target_Mean'] = df['JDGMNT_WORD_NAME_encoded'].mean()

print("[Critical-1] Target_Mean은 split 후 train만으로 fit/transform 한다.")
print("            현재 컬럼 'Target_Mean'은 임시 평균(상수)으로 placeholder.")
print("            실제 fit은 preprocess() 안의 fit_target_mean 호출에서 일어남.")

[Critical-1] Target_Mean은 split 후 train만으로 fit/transform 한다.
            현재 컬럼 'Target_Mean'은 임시 평균(상수)으로 placeholder.
            실제 fit은 preprocess() 안의 fit_target_mean 호출에서 일어남.

In [17]:
df.columns

Index(['tmprt_150_00', 'tmprt_150Top_00', 'tmprt_150Lwet_00', 'hd_150_00',
       'arvlty_300_00', 'arvlty_300Top_00', 'afp_00', 'solrad_Qy_00',
       'soil_Mitr_10_00', '일조_00',
       ...
       'INSPCT_PURPS_NAME', '결과', '결과값', '1차 식품 분류',
       'JDGMNT_WORD_NAME_encoded', '독소 생성 최적 온도 일수', '저습도 일수', '연속 무강수 일수',
       '교차_조합', 'Target_Mean'],
      dtype='object', length=510)

In [18]:
# [DEFECT-021 fix] iloc[:, : -10] positional slicing 제거 -> explicit prefix-pattern selection.
# 4 에이전트 회의 옵션 A 만장일치 (scientist/architect/critic/doc-spec) + critic 3 조건 만족 (assert 안전망).
# raw iloc 은 컬럼 순서/개수 의존 -> 미래 NB2 변경 시 silent label leakage 잠재 위험.
_ts_cols = [c for c in df.columns if any(c.startswith(f'{p}_') for p in timeseries_patterns)]
X_ts = df[_ts_cols]
assert X_ts.shape[1] == len(timeseries_patterns) * 50, f'X_ts shape mismatch: {X_ts.shape}'
assert not any(c in X_ts.columns for c in ['결과', '결과값', 'JDGMNT_WORD_NAME_encoded']), 'D-021 안전망: 라벨 컬럼 누설 검출'
print('X_ts shape:', X_ts.shape)
X_lm = df[['INSPCT_PURPS_NAME', '1차 식품 분류', '교차_조합', 'Target_Mean',
           '독소 생성 최적 온도 일수', '저습도 일수', '연속 무강수 일수']]
print('X_lm shape:', X_lm.shape)
print('X_lm columns:', X_lm.columns.tolist())

X_ts shape: (80883, 500)
X_lm shape: (80883, 7)
X_lm columns: ['INSPCT_PURPS_NAME', '1차 식품 분류', '교차_조합', 'Target_Mean', '독소 생성 최적 온도 일수', '저습도 일수', '연속 무강수 일수']

In [19]:
print(df[['INSPCT_PURPS_NAME', '1차 식품 분류', 'Target_Mean', '독소 생성 최적 온도 일수', '저습도 일수', '연속 무강수 일수']].dtypes)

INSPCT_PURPS_NAME     object
1차 식품 분류              object
Target_Mean          float64
독소 생성 최적 온도 일수         int64
저습도 일수                 int64
연속 무강수 일수            float64
dtype: object

## 1. 실험 데이터 1

In [20]:
y = df['JDGMNT_WORD_NAME_encoded']
y.value_counts(normalize=True)

JDGMNT_WORD_NAME_encoded
0    0.996093
1    0.003907
Name: proportion, dtype: float64

### [영역 M / Critical-1 · A-M1 · B-M3 · B-M5 · [D-008 fix] SMOTE 제거]
- **Critical-1**: Target_Mean의 cross_mean을 split 후 train fold 만으로 fit한다 (라벨 누설 차단).
- **A-M1**: 시계열 StandardScaler와 tabular StandardScaler 모두 split 이후 train으로만 fit하고 test에는 transform만 호출한다.
- **B-M3**: 운영 지표를 F1 → F2로 전환한다. [DEFECT-002 fix] EarlyStopping/ReduceLROnPlateau monitor='val_f2_grid_max' (F2GridMonitor callback 이 매 epoch val 데이터에서 99-threshold (0.01~0.99, evenly spaced) sweep 의 max F2 를 기록 → 보고용 find_optimal_threshold 와 동일 grid 이므로 monitor 의 best epoch 가 보고 best F2 의 best weight 와 수학적으로 일치). keras custom F2Score(threshold=0.5) 는 보조 metric (val_f2_score) 로 history 에만 남김. sklearn fbeta_score(beta=2) 로 final test 보고.
- **B-M5**: DummyClassifier(most_frequent / stratified) 베이스라인을 동일 test에 적용해 비교 표로 출력한다.
- **[D-008 fix] SMOTE 제거**: train fold 도 raw 0.5% 불균형 유지, class weighting (pos_weight = neg/pos) 으로 minority 처리. 시계열-tabular cross-space mismatch 차단.

2026-05-22 00:51:23.169368: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-05-22 00:51:23.169612: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-05-22 00:51:23.171634: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-05-22 00:51:23.183786: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

2026-05-22 00:51:25.461043: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

[DEFECT-001 fix / split] train=56617 (70.0%), val=12133 (15.0%), test=12133 (15.0%)
  train pos=222, val pos=47, test pos=47

[A-M1 / 시계열 scaler] fit on train only. mean[:3]=[12.544  18.4217  7.454 ], scale[:3]=[10.4582 11.057  10.7873]
[Critical-1 / Target_Mean] fit on train only. unique 조합=89, fallback=0.0039
  train Target_Mean stat: min=0.0001, max=0.0717, mean=0.0038
[A-M1 / tabular num scaler] fit on train only. mean=[3.8000e-03 9.3910e-01 1.7271e+00 4.5210e+00], scale=[0.0043 2.1115 2.3988 2.0226]

[최종 체크 — DEFECT-008 fix: SMOTE 제거]
  X_ts_train shape=(56617, 50, 10), NaN=0, Inf=0
  X_lm_train_arr shape=(56617, 39), NaN=0, Inf=0
  y_train 클래스 1 비율 (raw, no SMOTE): 0.0039
  X_ts_val shape=(12133, 50, 10), X_lm_val_arr shape=(12133, 39), y_val 클래스 1 비율=0.0039
  X_ts_test shape=(12133, 50, 10), X_lm_test_arr shape=(12133, 39), y_test 클래스 1 비율=0.0039

Training shapes (DEFECT-008 fix — SMOTE 제거, raw 0.5% 불균형 유지):
  X_ts_train: (56617, 50, 10)
  X_tab_train: (56617, 39)
  y_train: (56617,), 클래스 1 비율: 0.0039

Validation shapes (No SMOTE — 원본 0.5% 불균형 유지):
  X_ts_val: (12133, 50, 10), X_tab_val: (12133, 39)
  y_val: (12133,), 클래스 1 비율: 0.0039

Test shapes (No SMOTE — final 평가, 단 1회):
  X_ts_test: (12133, 50, 10), X_tab_test: (12133, 39)
  y_test: (12133,), 클래스 1 비율: 0.0039

==================================================
Hybrid LSTM+FNN 학습 (Weighted BCE + F2 monitor)
==================================================

[학습 전 데이터 검증]

  X_ts_train: NaN=0, Inf=0
  X_tab_train: NaN=0, Inf=0

[클래스 불균형 분석]
  클래스 0: 56395개, 클래스 1: 222개
  불균형 비율: 1:254.0, pos_weight: 254.03

2026-05-22 00:51:30.117930: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:4d:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-05-22 00:51:30.359308: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:4d:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-05-22 00:51:30.362968: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:4d:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-05-22 00:51:30.371913: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:4d:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-05-22 00:51:30.375554: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:4d:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-05-22 00:51:30.379095: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:4d:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-05-22 00:51:30.500998: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:4d:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-05-22 00:51:30.502735: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:4d:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-05-22 00:51:30.504303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2022] Could not identify NUMA node of platform GPU id 0, defaulting to 0.  Your kernel may not have been built with NUMA support.
2026-05-22 00:51:30.504445: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:4d:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-05-22 00:51:30.506071: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 20833 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:4d:00.0, compute capability: 8.9
2026-05-22 00:51:30.736170: I external/local_tsl/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory

[손실] Weighted BCE (pos_weight=254.03)

Epoch 1/50

2026-05-22 00:51:47.570722: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:454] Loaded cuDNN version 8904

2026-05-22 00:51:50.896908: I external/local_xla/xla/service/service.cc:168] XLA service 0x2b4ed402f9e0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2026-05-22 00:51:50.897058: I external/local_xla/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
2026-05-22 00:51:50.906976: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1779411111.011219      65 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

  1/222 [..............................] - ETA: 1:16:24 - loss: 4.2481 - recall: 0.0000e+00 - precision: 0.0000e+00 - f2_score: 0.0000e+00 - auc: 0.0216 - pr_auc: 0.0020

  4/222 [..............................] - ETA: 4s - loss: 2.4903 - recall: 0.3333 - precision: 0.0021 - f2_score: 0.0102 - auc: 0.3914 - pr_auc: 0.0026

  7/222 [..............................] - ETA: 4s - loss: 2.4484 - recall: 0.4286 - precision: 0.0035 - f2_score: 0.0170 - auc: 0.4505 - pr_auc: 0.0033

 10/222 [>.............................] - ETA: 4s - loss: 2.1578 - recall: 0.5000 - precision: 0.0033 - f2_score: 0.0159 - auc: 0.4942 - pr_auc: 0.0029

 13/222 [>.............................] - ETA: 4s - loss: 2.0102 - recall: 0.6364 - precision: 0.0044 - f2_score: 0.0213 - auc: 0.5995 - pr_auc: 0.0094

 16/222 [=>............................] - ETA: 4s - loss: 2.0476 - recall: 0.6000 - precision: 0.0045 - f2_score: 0.0221 - auc: 0.5955 - pr_auc: 0.0190

 19/222 [=>............................] - ETA: 4s - loss: 2.0183 - recall: 0.5882 - precision: 0.0043 - f2_score: 0.0208 - auc: 0.5863 - pr_auc: 0.0145

 22/222 [=>............................] - ETA: 4s - loss: 2.1144 - recall: 0.5500 - precision: 0.0041 - f2_score: 0.0198 - auc: 0.5542 - pr_auc: 0.0109

 25/222 [==>...........................] - ETA: 4s - loss: 2.2487 - recall: 0.4783 - precision: 0.0036 - f2_score: 0.0175 - auc: 0.5042 - pr_auc: 0.0087

 28/222 [==>...........................] - ETA: 3s - loss: 2.3105 - recall: 0.4643 - precision: 0.0038 - f2_score: 0.0185 - auc: 0.4965 - pr_auc: 0.0077

 31/222 [===>..........................] - ETA: 3s - loss: 2.2875 - recall: 0.5000 - precision: 0.0042 - f2_score: 0.0205 - auc: 0.5149 - pr_auc: 0.0074

 34/222 [===>..........................] - ETA: 3s - loss: 2.2577 - recall: 0.5143 - precision: 0.0043 - f2_score: 0.0209 - auc: 0.5204 - pr_auc: 0.0068

 37/222 [====>.........................] - ETA: 3s - loss: 2.2858 - recall: 0.4737 - precision: 0.0040 - f2_score: 0.0192 - auc: 0.5013 - pr_auc: 0.0061

 40/222 [====>.........................] - ETA: 3s - loss: 2.2170 - recall: 0.4737 - precision: 0.0037 - f2_score: 0.0178 - auc: 0.5014 - pr_auc: 0.0056

 43/222 [====>.........................] - ETA: 3s - loss: 2.2128 - recall: 0.4878 - precision: 0.0038 - f2_score: 0.0183 - auc: 0.5037 - pr_auc: 0.0053

 46/222 [=====>........................] - ETA: 3s - loss: 2.2243 - recall: 0.5000 - precision: 0.0039 - f2_score: 0.0188 - auc: 0.5019 - pr_auc: 0.0051

 49/222 [=====>........................] - ETA: 3s - loss: 2.2288 - recall: 0.4783 - precision: 0.0036 - f2_score: 0.0177 - auc: 0.4889 - pr_auc: 0.0048

 52/222 [======>.......................] - ETA: 3s - loss: 2.2457 - recall: 0.4800 - precision: 0.0038 - f2_score: 0.0182 - auc: 0.4927 - pr_auc: 0.0050

 55/222 [======>.......................] - ETA: 3s - loss: 2.2254 - recall: 0.4706 - precision: 0.0035 - f2_score: 0.0172 - auc: 0.4861 - pr_auc: 0.0047

 58/222 [======>.......................] - ETA: 3s - loss: 2.2038 - recall: 0.4815 - precision: 0.0036 - f2_score: 0.0177 - auc: 0.4963 - pr_auc: 0.0047

 61/222 [=======>......................] - ETA: 3s - loss: 2.1820 - recall: 0.4821 - precision: 0.0036 - f2_score: 0.0175 - auc: 0.5007 - pr_auc: 0.0047

 64/222 [=======>......................] - ETA: 3s - loss: 2.1877 - recall: 0.4746 - precision: 0.0036 - f2_score: 0.0172 - auc: 0.4988 - pr_auc: 0.0046

 67/222 [========>.....................] - ETA: 2s - loss: 2.2282 - recall: 0.4844 - precision: 0.0038 - f2_score: 0.0182 - auc: 0.4945 - pr_auc: 0.0046

 70/222 [========>.....................] - ETA: 2s - loss: 2.2014 - recall: 0.4769 - precision: 0.0036 - f2_score: 0.0174 - auc: 0.4945 - pr_auc: 0.0044

 73/222 [========>.....................] - ETA: 2s - loss: 2.2000 - recall: 0.4853 - precision: 0.0037 - f2_score: 0.0178 - auc: 0.4957 - pr_auc: 0.0043

 76/222 [=========>....................] - ETA: 2s - loss: 2.1757 - recall: 0.5070 - precision: 0.0038 - f2_score: 0.0187 - auc: 0.5102 - pr_auc: 0.0045

 79/222 [=========>....................] - ETA: 2s - loss: 2.1762 - recall: 0.4932 - precision: 0.0037 - f2_score: 0.0179 - auc: 0.5029 - pr_auc: 0.0043

 82/222 [==========>...................] - ETA: 2s - loss: 2.1738 - recall: 0.5065 - precision: 0.0039 - f2_score: 0.0187 - auc: 0.5084 - pr_auc: 0.0044

 85/222 [==========>...................] - ETA: 2s - loss: 2.1514 - recall: 0.5190 - precision: 0.0039 - f2_score: 0.0190 - auc: 0.5152 - pr_auc: 0.0044

 88/222 [==========>...................] - ETA: 2s - loss: 2.1518 - recall: 0.5301 - precision: 0.0041 - f2_score: 0.0197 - auc: 0.5179 - pr_auc: 0.0044

 91/222 [===========>..................] - ETA: 2s - loss: 2.1789 - recall: 0.5172 - precision: 0.0040 - f2_score: 0.0195 - auc: 0.5114 - pr_auc: 0.0044

 94/222 [===========>..................] - ETA: 2s - loss: 2.1829 - recall: 0.5217 - precision: 0.0042 - f2_score: 0.0201 - auc: 0.5160 - pr_auc: 0.0050

 97/222 [============>.................] - ETA: 2s - loss: 2.1846 - recall: 0.5158 - precision: 0.0041 - f2_score: 0.0199 - auc: 0.5156 - pr_auc: 0.0050

100/222 [============>.................] - ETA: 2s - loss: 2.1770 - recall: 0.5300 - precision: 0.0043 - f2_score: 0.0209 - auc: 0.5273 - pr_auc: 0.0059

103/222 [============>.................] - ETA: 2s - loss: 2.2030 - recall: 0.5238 - precision: 0.0044 - f2_score: 0.0211 - auc: 0.5239 - pr_auc: 0.0058

106/222 [=============>................] - ETA: 2s - loss: 2.1953 - recall: 0.5234 - precision: 0.0043 - f2_score: 0.0208 - auc: 0.5237 - pr_auc: 0.0058

109/222 [=============>................] - ETA: 2s - loss: 2.1730 - recall: 0.5278 - precision: 0.0043 - f2_score: 0.0206 - auc: 0.5269 - pr_auc: 0.0057

112/222 [==============>...............] - ETA: 2s - loss: 2.1848 - recall: 0.5357 - precision: 0.0044 - f2_score: 0.0211 - auc: 0.5321 - pr_auc: 0.0065

115/222 [==============>...............] - ETA: 1s - loss: 2.1770 - recall: 0.5263 - precision: 0.0042 - f2_score: 0.0206 - auc: 0.5305 - pr_auc: 0.0064

118/222 [==============>...............] - ETA: 1s - loss: 2.1735 - recall: 0.5259 - precision: 0.0042 - f2_score: 0.0204 - auc: 0.5303 - pr_auc: 0.0063

121/222 [===============>..............] - ETA: 1s - loss: 2.1903 - recall: 0.5246 - precision: 0.0043 - f2_score: 0.0209 - auc: 0.5334 - pr_auc: 0.0066

124/222 [===============>..............] - ETA: 1s - loss: 2.1941 - recall: 0.5161 - precision: 0.0042 - f2_score: 0.0204 - auc: 0.5277 - pr_auc: 0.0064

127/222 [================>.............] - ETA: 1s - loss: 2.1737 - recall: 0.5161 - precision: 0.0041 - f2_score: 0.0199 - auc: 0.5277 - pr_auc: 0.0063

130/222 [================>.............] - ETA: 1s - loss: 2.1694 - recall: 0.5312 - precision: 0.0043 - f2_score: 0.0207 - auc: 0.5314 - pr_auc: 0.0062

133/222 [================>.............] - ETA: 1s - loss: 2.1653 - recall: 0.5344 - precision: 0.0043 - f2_score: 0.0208 - auc: 0.5325 - pr_auc: 0.0061

136/222 [=================>............] - ETA: 1s - loss: 2.1552 - recall: 0.5338 - precision: 0.0043 - f2_score: 0.0207 - auc: 0.5338 - pr_auc: 0.0061

139/222 [=================>............] - ETA: 1s - loss: 2.1414 - recall: 0.5407 - precision: 0.0043 - f2_score: 0.0208 - auc: 0.5374 - pr_auc: 0.0061

142/222 [==================>...........] - ETA: 1s - loss: 2.1338 - recall: 0.5435 - precision: 0.0043 - f2_score: 0.0209 - auc: 0.5402 - pr_auc: 0.0061

145/222 [==================>...........] - ETA: 1s - loss: 2.1281 - recall: 0.5429 - precision: 0.0043 - f2_score: 0.0207 - auc: 0.5398 - pr_auc: 0.0060

148/222 [===================>..........] - ETA: 1s - loss: 2.1316 - recall: 0.5385 - precision: 0.0042 - f2_score: 0.0206 - auc: 0.5385 - pr_auc: 0.0061

151/222 [===================>..........] - ETA: 1s - loss: 2.1492 - recall: 0.5467 - precision: 0.0044 - f2_score: 0.0215 - auc: 0.5400 - pr_auc: 0.0067

154/222 [===================>..........] - ETA: 1s - loss: 2.1846 - recall: 0.5346 - precision: 0.0045 - f2_score: 0.0218 - auc: 0.5347 - pr_auc: 0.0065

157/222 [====================>.........] - ETA: 1s - loss: 2.2076 - recall: 0.5305 - precision: 0.0045 - f2_score: 0.0219 - auc: 0.5286 - pr_auc: 0.0064

160/222 [====================>.........] - ETA: 1s - loss: 2.2004 - recall: 0.5417 - precision: 0.0046 - f2_score: 0.0225 - auc: 0.5335 - pr_auc: 0.0065

163/222 [=====================>........] - ETA: 1s - loss: 2.1891 - recall: 0.5412 - precision: 0.0046 - f2_score: 0.0223 - auc: 0.5357 - pr_auc: 0.0069

166/222 [=====================>........] - ETA: 1s - loss: 2.1877 - recall: 0.5460 - precision: 0.0047 - f2_score: 0.0226 - auc: 0.5373 - pr_auc: 0.0068

169/222 [=====================>........] - ETA: 0s - loss: 2.1719 - recall: 0.5486 - precision: 0.0046 - f2_score: 0.0225 - auc: 0.5400 - pr_auc: 0.0069

172/222 [======================>.......] - ETA: 0s - loss: 2.1779 - recall: 0.5449 - precision: 0.0046 - f2_score: 0.0223 - auc: 0.5376 - pr_auc: 0.0071

175/222 [======================>.......] - ETA: 0s - loss: 2.1787 - recall: 0.5414 - precision: 0.0046 - f2_score: 0.0222 - auc: 0.5362 - pr_auc: 0.0070

178/222 [=======================>......] - ETA: 0s - loss: 2.1669 - recall: 0.5440 - precision: 0.0045 - f2_score: 0.0220 - auc: 0.5368 - pr_auc: 0.0069

181/222 [=======================>......] - ETA: 0s - loss: 2.1640 - recall: 0.5459 - precision: 0.0046 - f2_score: 0.0221 - auc: 0.5365 - pr_auc: 0.0068

184/222 [=======================>......] - ETA: 0s - loss: 2.1510 - recall: 0.5484 - precision: 0.0045 - f2_score: 0.0219 - auc: 0.5383 - pr_auc: 0.0068

187/222 [========================>.....] - ETA: 0s - loss: 2.1543 - recall: 0.5474 - precision: 0.0045 - f2_score: 0.0220 - auc: 0.5384 - pr_auc: 0.0069

190/222 [========================>.....] - ETA: 0s - loss: 2.1590 - recall: 0.5487 - precision: 0.0046 - f2_score: 0.0223 - auc: 0.5390 - pr_auc: 0.0070

193/222 [=========================>....] - ETA: 0s - loss: 2.1457 - recall: 0.5487 - precision: 0.0045 - f2_score: 0.0219 - auc: 0.5389 - pr_auc: 0.0069

196/222 [=========================>....] - ETA: 0s - loss: 2.1412 - recall: 0.5482 - precision: 0.0045 - f2_score: 0.0218 - auc: 0.5383 - pr_auc: 0.0068

199/222 [=========================>....] - ETA: 0s - loss: 2.1292 - recall: 0.5528 - precision: 0.0045 - f2_score: 0.0218 - auc: 0.5426 - pr_auc: 0.0073

202/222 [==========================>...] - ETA: 0s - loss: 2.1184 - recall: 0.5572 - precision: 0.0045 - f2_score: 0.0219 - auc: 0.5462 - pr_auc: 0.0078

205/222 [==========================>...] - ETA: 0s - loss: 2.1228 - recall: 0.5631 - precision: 0.0046 - f2_score: 0.0224 - auc: 0.5487 - pr_auc: 0.0081

208/222 [===========================>..] - ETA: 0s - loss: 2.1224 - recall: 0.5625 - precision: 0.0046 - f2_score: 0.0222 - auc: 0.5466 - pr_auc: 0.0079

211/222 [===========================>..] - ETA: 0s - loss: 2.1184 - recall: 0.5571 - precision: 0.0045 - f2_score: 0.0219 - auc: 0.5456 - pr_auc: 0.0079

214/222 [===========================>..] - ETA: 0s - loss: 2.1302 - recall: 0.5576 - precision: 0.0046 - f2_score: 0.0223 - auc: 0.5465 - pr_auc: 0.0079

217/222 [============================>.] - ETA: 0s - loss: 2.1189 - recall: 0.5576 - precision: 0.0045 - f2_score: 0.0220 - auc: 0.5465 - pr_auc: 0.0078

220/222 [============================>.] - ETA: 0s - loss: 2.1152 - recall: 0.5545 - precision: 0.0045 - f2_score: 0.0219 - auc: 0.5476 - pr_auc: 0.0082

  [F2GridMonitor] val_f2_grid_max=0.0649 @ th=0.59
222/222 [==============================] - 33s 53ms/step - loss: 2.1135 - recall: 0.5586 - precision: 0.0046 - f2_score: 0.0221 - auc: 0.5498 - pr_auc: 0.0088 - val_loss: 1.8124 - val_recall: 0.1489 - val_precision: 0.0074 - val_f2_score: 0.0310 - val_auc: 0.5863 - val_pr_auc: 0.0085 - val_f2_grid_max: 0.0649 - val_f2_best_th: 0.5900 - lr: 1.0000e-04

Epoch 2/50

  1/222 [..............................] - ETA: 5s - loss: 1.3382 - recall: 0.0000e+00 - precision: 0.0000e+00 - f2_score: 0.0000e+00 - auc: 0.0000e+00 - pr_auc: 0.0000e+00

  4/222 [..............................] - ETA: 4s - loss: 1.5601 - recall: 0.5000 - precision: 0.0020 - f2_score: 0.0100 - auc: 0.6414 - pr_auc: 0.0026

  7/222 [..............................] - ETA: 4s - loss: 1.5175 - recall: 0.6667 - precision: 0.0024 - f2_score: 0.0116 - auc: 0.6382 - pr_auc: 0.0021

 10/222 [>.............................] - ETA: 4s - loss: 1.7296 - recall: 0.5000 - precision: 0.0025 - f2_score: 0.0123 - auc: 0.5586 - pr_auc: 0.0026

 13/222 [>.............................] - ETA: 4s - loss: 1.7506 - recall: 0.5000 - precision: 0.0026 - f2_score: 0.0126 - auc: 0.5519 - pr_auc: 0.0027

 16/222 [=>............................] - ETA: 4s - loss: 1.7165 - recall: 0.6364 - precision: 0.0036 - f2_score: 0.0175 - auc: 0.6281 - pr_auc: 0.0041

 19/222 [=>............................] - ETA: 4s - loss: 1.7675 - recall: 0.6154 - precision: 0.0034 - f2_score: 0.0168 - auc: 0.6076 - pr_auc: 0.0041

 22/222 [=>............................] - ETA: 4s - loss: 1.8552 - recall: 0.5882 - precision: 0.0037 - f2_score: 0.0181 - auc: 0.5968 - pr_auc: 0.0045

 25/222 [==>...........................] - ETA: 4s - loss: 1.8195 - recall: 0.5556 - precision: 0.0033 - f2_score: 0.0160 - auc: 0.5874 - pr_auc: 0.0040

 28/222 [==>...........................] - ETA: 4s - loss: 1.8642 - recall: 0.6250 - precision: 0.0044 - f2_score: 0.0214 - auc: 0.6160 - pr_auc: 0.0051

 31/222 [===>..........................] - ETA: 3s - loss: 1.9619 - recall: 0.6000 - precision: 0.0048 - f2_score: 0.0231 - auc: 0.5922 - pr_auc: 0.0053

 34/222 [===>..........................] - ETA: 3s - loss: 1.9410 - recall: 0.5806 - precision: 0.0044 - f2_score: 0.0211 - auc: 0.5801 - pr_auc: 0.0048

 37/222 [====>.........................] - ETA: 3s - loss: 2.0223 - recall: 0.5882 - precision: 0.0044 - f2_score: 0.0215 - auc: 0.5692 - pr_auc: 0.0046

 40/222 [====>.........................] - ETA: 3s - loss: 2.0361 - recall: 0.5676 - precision: 0.0043 - f2_score: 0.0208 - auc: 0.5556 - pr_auc: 0.0044

 43/222 [====>.........................] - ETA: 3s - loss: 2.0587 - recall: 0.6047 - precision: 0.0050 - f2_score: 0.0240 - auc: 0.5696 - pr_auc: 0.0047

 46/222 [=====>........................] - ETA: 3s - loss: 2.0449 - recall: 0.6000 - precision: 0.0048 - f2_score: 0.0233 - auc: 0.5667 - pr_auc: 0.0046

 49/222 [=====>........................] - ETA: 3s - loss: 2.0092 - recall: 0.6170 - precision: 0.0049 - f2_score: 0.0236 - auc: 0.5772 - pr_auc: 0.0054

 52/222 [======>.......................] - ETA: 3s - loss: 1.9847 - recall: 0.6122 - precision: 0.0047 - f2_score: 0.0230 - auc: 0.5825 - pr_auc: 0.0054

 55/222 [======>.......................] - ETA: 3s - loss: 2.0015 - recall: 0.6296 - precision: 0.0051 - f2_score: 0.0246 - auc: 0.5875 - pr_auc: 0.0055

 58/222 [======>.......................] - ETA: 3s - loss: 2.0341 - recall: 0.6452 - precision: 0.0057 - f2_score: 0.0274 - auc: 0.6011 - pr_auc: 0.0069

 61/222 [=======>......................] - ETA: 3s - loss: 2.0224 - recall: 0.6349 - precision: 0.0054 - f2_score: 0.0260 - auc: 0.5936 - pr_auc: 0.0065

 64/222 [=======>......................] - ETA: 3s - loss: 2.0633 - recall: 0.6364 - precision: 0.0054 - f2_score: 0.0260 - auc: 0.5838 - pr_auc: 0.0063

 67/222 [========>.....................] - ETA: 3s - loss: 2.0284 - recall: 0.6364 - precision: 0.0051 - f2_score: 0.0249 - auc: 0.5835 - pr_auc: 0.0060

 70/222 [========>.....................] - ETA: 3s - loss: 2.0256 - recall: 0.6377 - precision: 0.0051 - f2_score: 0.0249 - auc: 0.5814 - pr_auc: 0.0058

 73/222 [========>.....................] - ETA: 2s - loss: 2.0175 - recall: 0.6438 - precision: 0.0053 - f2_score: 0.0255 - auc: 0.5900 - pr_auc: 0.0059

 76/222 [=========>....................] - ETA: 2s - loss: 1.9937 - recall: 0.6486 - precision: 0.0052 - f2_score: 0.0251 - auc: 0.5922 - pr_auc: 0.0058

 79/222 [=========>....................] - ETA: 2s - loss: 2.0759 - recall: 0.6220 - precision: 0.0053 - f2_score: 0.0256 - auc: 0.5704 - pr_auc: 0.0056

 82/222 [==========>...................] - ETA: 2s - loss: 2.0856 - recall: 0.6444 - precision: 0.0058 - f2_score: 0.0279 - auc: 0.5848 - pr_auc: 0.0083

 85/222 [==========>...................] - ETA: 2s - loss: 2.1087 - recall: 0.6421 - precision: 0.0059 - f2_score: 0.0283 - auc: 0.5804 - pr_auc: 0.0080

 88/222 [==========>...................] - ETA: 2s - loss: 2.0894 - recall: 0.6354 - precision: 0.0057 - f2_score: 0.0274 - auc: 0.5789 - pr_auc: 0.0078

 91/222 [===========>..................] - ETA: 2s - loss: 2.0824 - recall: 0.6327 - precision: 0.0056 - f2_score: 0.0270 - auc: 0.5772 - pr_auc: 0.0075

 94/222 [===========>..................] - ETA: 2s - loss: 2.0737 - recall: 0.6436 - precision: 0.0057 - f2_score: 0.0274 - auc: 0.5789 - pr_auc: 0.0074

 97/222 [============>.................] - ETA: 2s - loss: 2.0616 - recall: 0.6538 - precision: 0.0057 - f2_score: 0.0278 - auc: 0.5839 - pr_auc: 0.0073

100/222 [============>.................] - ETA: 2s - loss: 2.0612 - recall: 0.6415 - precision: 0.0056 - f2_score: 0.0269 - auc: 0.5783 - pr_auc: 0.0071

103/222 [============>.................] - ETA: 2s - loss: 2.0595 - recall: 0.6396 - precision: 0.0057 - f2_score: 0.0273 - auc: 0.5851 - pr_auc: 0.0084

106/222 [=============>................] - ETA: 2s - loss: 2.0587 - recall: 0.6283 - precision: 0.0055 - f2_score: 0.0265 - auc: 0.5800 - pr_auc: 0.0081

109/222 [=============>................] - ETA: 2s - loss: 2.0448 - recall: 0.6228 - precision: 0.0053 - f2_score: 0.0258 - auc: 0.5790 - pr_auc: 0.0078

112/222 [==============>...............] - ETA: 2s - loss: 2.0341 - recall: 0.6207 - precision: 0.0053 - f2_score: 0.0255 - auc: 0.5806 - pr_auc: 0.0076

115/222 [==============>...............] - ETA: 2s - loss: 2.0316 - recall: 0.6134 - precision: 0.0052 - f2_score: 0.0252 - auc: 0.5801 - pr_auc: 0.0075

118/222 [==============>...............] - ETA: 1s - loss: 2.0160 - recall: 0.6167 - precision: 0.0051 - f2_score: 0.0249 - auc: 0.5817 - pr_auc: 0.0073

121/222 [===============>..............] - ETA: 1s - loss: 2.0069 - recall: 0.6179 - precision: 0.0052 - f2_score: 0.0250 - auc: 0.5863 - pr_auc: 0.0072

124/222 [===============>..............] - ETA: 1s - loss: 1.9903 - recall: 0.6210 - precision: 0.0051 - f2_score: 0.0247 - auc: 0.5893 - pr_auc: 0.0072

127/222 [================>.............] - ETA: 1s - loss: 1.9890 - recall: 0.6250 - precision: 0.0052 - f2_score: 0.0250 - auc: 0.5925 - pr_auc: 0.0072

130/222 [================>.............] - ETA: 1s - loss: 1.9858 - recall: 0.6231 - precision: 0.0051 - f2_score: 0.0248 - auc: 0.5907 - pr_auc: 0.0070

133/222 [================>.............] - ETA: 1s - loss: 1.9785 - recall: 0.6241 - precision: 0.0051 - f2_score: 0.0248 - auc: 0.5945 - pr_auc: 0.0071

136/222 [=================>............] - ETA: 1s - loss: 1.9768 - recall: 0.6222 - precision: 0.0051 - f2_score: 0.0245 - auc: 0.5924 - pr_auc: 0.0070

139/222 [=================>............] - ETA: 1s - loss: 1.9691 - recall: 0.6304 - precision: 0.0051 - f2_score: 0.0249 - auc: 0.5969 - pr_auc: 0.0069

142/222 [==================>...........] - ETA: 1s - loss: 1.9659 - recall: 0.6383 - precision: 0.0052 - f2_score: 0.0252 - auc: 0.5981 - pr_auc: 0.0068

145/222 [==================>...........] - ETA: 1s - loss: 1.9598 - recall: 0.6364 - precision: 0.0051 - f2_score: 0.0249 - auc: 0.5983 - pr_auc: 0.0067

148/222 [===================>..........] - ETA: 1s - loss: 1.9730 - recall: 0.6351 - precision: 0.0052 - f2_score: 0.0252 - auc: 0.5972 - pr_auc: 0.0067

151/222 [===================>..........] - ETA: 1s - loss: 1.9840 - recall: 0.6316 - precision: 0.0052 - f2_score: 0.0252 - auc: 0.5939 - pr_auc: 0.0066

154/222 [===================>..........] - ETA: 1s - loss: 1.9875 - recall: 0.6258 - precision: 0.0052 - f2_score: 0.0250 - auc: 0.5903 - pr_auc: 0.0065

157/222 [====================>.........] - ETA: 1s - loss: 1.9738 - recall: 0.6258 - precision: 0.0051 - f2_score: 0.0245 - auc: 0.5903 - pr_auc: 0.0064

160/222 [====================>.........] - ETA: 1s - loss: 1.9600 - recall: 0.6258 - precision: 0.0050 - f2_score: 0.0241 - auc: 0.5905 - pr_auc: 0.0063

163/222 [=====================>........] - ETA: 1s - loss: 1.9643 - recall: 0.6273 - precision: 0.0051 - f2_score: 0.0246 - auc: 0.5944 - pr_auc: 0.0063

166/222 [=====================>........] - ETA: 1s - loss: 1.9643 - recall: 0.6242 - precision: 0.0051 - f2_score: 0.0246 - auc: 0.5963 - pr_auc: 0.0063

169/222 [=====================>........] - ETA: 1s - loss: 1.9619 - recall: 0.6250 - precision: 0.0051 - f2_score: 0.0247 - auc: 0.5968 - pr_auc: 0.0068

172/222 [======================>.......] - ETA: 0s - loss: 1.9721 - recall: 0.6176 - precision: 0.0050 - f2_score: 0.0242 - auc: 0.5926 - pr_auc: 0.0067

175/222 [======================>.......] - ETA: 0s - loss: 1.9851 - recall: 0.6114 - precision: 0.0050 - f2_score: 0.0243 - auc: 0.5884 - pr_auc: 0.0066

178/222 [=======================>......] - ETA: 0s - loss: 1.9972 - recall: 0.6034 - precision: 0.0050 - f2_score: 0.0241 - auc: 0.5839 - pr_auc: 0.0065

181/222 [=======================>......] - ETA: 0s - loss: 1.9959 - recall: 0.5967 - precision: 0.0049 - f2_score: 0.0237 - auc: 0.5813 - pr_auc: 0.0064

184/222 [=======================>......] - ETA: 0s - loss: 1.9998 - recall: 0.5902 - precision: 0.0048 - f2_score: 0.0233 - auc: 0.5774 - pr_auc: 0.0063

187/222 [========================>.....] - ETA: 0s - loss: 1.9970 - recall: 0.5892 - precision: 0.0048 - f2_score: 0.0232 - auc: 0.5761 - pr_auc: 0.0062

190/222 [========================>.....] - ETA: 0s - loss: 2.0032 - recall: 0.5798 - precision: 0.0047 - f2_score: 0.0228 - auc: 0.5716 - pr_auc: 0.0061

193/222 [=========================>....] - ETA: 0s - loss: 2.0003 - recall: 0.5812 - precision: 0.0047 - f2_score: 0.0229 - auc: 0.5731 - pr_auc: 0.0061

196/222 [=========================>....] - ETA: 0s - loss: 2.0131 - recall: 0.5850 - precision: 0.0049 - f2_score: 0.0237 - auc: 0.5777 - pr_auc: 0.0064

199/222 [=========================>....] - ETA: 0s - loss: 2.0055 - recall: 0.5891 - precision: 0.0049 - f2_score: 0.0238 - auc: 0.5797 - pr_auc: 0.0064

202/222 [==========================>...] - ETA: 0s - loss: 1.9948 - recall: 0.5891 - precision: 0.0048 - f2_score: 0.0235 - auc: 0.5796 - pr_auc: 0.0063

205/222 [==========================>...] - ETA: 0s - loss: 1.9944 - recall: 0.5942 - precision: 0.0049 - f2_score: 0.0239 - auc: 0.5836 - pr_auc: 0.0063

208/222 [===========================>..] - ETA: 0s - loss: 1.9911 - recall: 0.5933 - precision: 0.0049 - f2_score: 0.0237 - auc: 0.5830 - pr_auc: 0.0062

211/222 [===========================>..] - ETA: 0s - loss: 1.9832 - recall: 0.5952 - precision: 0.0049 - f2_score: 0.0236 - auc: 0.5835 - pr_auc: 0.0062

214/222 [===========================>..] - ETA: 0s - loss: 1.9874 - recall: 0.5907 - precision: 0.0049 - f2_score: 0.0236 - auc: 0.5843 - pr_auc: 0.0066

217/222 [============================>.] - ETA: 0s - loss: 1.9831 - recall: 0.5982 - precision: 0.0050 - f2_score: 0.0241 - auc: 0.5881 - pr_auc: 0.0068

220/222 [============================>.] - ETA: 0s - loss: 1.9806 - recall: 0.5928 - precision: 0.0049 - f2_score: 0.0238 - auc: 0.5868 - pr_auc: 0.0067

  [F2GridMonitor] val_f2_grid_max=0.1054 @ th=0.67
222/222 [==============================] - 7s 30ms/step - loss: 1.9832 - recall: 0.5901 - precision: 0.0049 - f2_score: 0.0236 - auc: 0.5850 - pr_auc: 0.0067 - val_loss: 1.7174 - val_recall: 0.4468 - val_precision: 0.0079 - val_f2_score: 0.0370 - val_auc: 0.6757 - val_pr_auc: 0.0135 - val_f2_grid_max: 0.1054 - val_f2_best_th: 0.6700 - lr: 1.0000e-04

Epoch 3/50

  1/222 [..............................] - ETA: 4s - loss: 1.8830 - recall: 1.0000 - precision: 0.0168 - f2_score: 0.0787 - auc: 0.8189 - pr_auc: 0.0305

  4/222 [..............................] - ETA: 4s - loss: 1.7762 - recall: 1.0000 - precision: 0.0143 - f2_score: 0.0677 - auc: 0.8354 - pr_auc: 0.0218

  7/222 [..............................] - ETA: 3s - loss: 2.1218 - recall: 0.7500 - precision: 0.0107 - f2_score: 0.0507 - auc: 0.7037 - pr_auc: 0.0136

 10/222 [>.............................] - ETA: 3s - loss: 2.1141 - recall: 0.7333 - precision: 0.0090 - f2_score: 0.0430 - auc: 0.6547 - pr_auc: 0.0098

 13/222 [>.............................] - ETA: 3s - loss: 2.1633 - recall: 0.6667 - precision: 0.0076 - f2_score: 0.0364 - auc: 0.6082 - pr_auc: 0.0076

 16/222 [=>............................] - ETA: 3s - loss: 2.0526 - recall: 0.7000 - precision: 0.0073 - f2_score: 0.0350 - auc: 0.6172 - pr_auc: 0.0067

 19/222 [=>............................] - ETA: 3s - loss: 2.0050 - recall: 0.6957 - precision: 0.0070 - f2_score: 0.0338 - auc: 0.6283 - pr_auc: 0.0070

 22/222 [=>............................] - ETA: 3s - loss: 1.9422 - recall: 0.6667 - precision: 0.0061 - f2_score: 0.0294 - auc: 0.6195 - pr_auc: 0.0061

 25/222 [==>...........................] - ETA: 3s - loss: 1.8850 - recall: 0.7037 - precision: 0.0064 - f2_score: 0.0307 - auc: 0.6505 - pr_auc: 0.0072

 28/222 [==>...........................] - ETA: 3s - loss: 1.8719 - recall: 0.7000 - precision: 0.0063 - f2_score: 0.0303 - auc: 0.6538 - pr_auc: 0.0069

 31/222 [===>..........................] - ETA: 3s - loss: 1.8136 - recall: 0.7000 - precision: 0.0057 - f2_score: 0.0275 - auc: 0.6533 - pr_auc: 0.0062

 34/222 [===>..........................] - ETA: 3s - loss: 1.7648 - recall: 0.7000 - precision: 0.0052 - f2_score: 0.0252 - auc: 0.6538 - pr_auc: 0.0057

 37/222 [====>.........................] - ETA: 3s - loss: 1.8165 - recall: 0.6571 - precision: 0.0052 - f2_score: 0.0254 - auc: 0.6408 - pr_auc: 0.0057

 40/222 [====>.........................] - ETA: 3s - loss: 1.7895 - recall: 0.6667 - precision: 0.0050 - f2_score: 0.0245 - auc: 0.6395 - pr_auc: 0.0054

 43/222 [====>.........................] - ETA: 3s - loss: 1.7564 - recall: 0.6757 - precision: 0.0049 - f2_score: 0.0238 - auc: 0.6469 - pr_auc: 0.0053

 46/222 [=====>........................] - ETA: 3s - loss: 1.8204 - recall: 0.6429 - precision: 0.0049 - f2_score: 0.0240 - auc: 0.6220 - pr_auc: 0.0051

 49/222 [=====>........................] - ETA: 3s - loss: 1.8018 - recall: 0.6444 - precision: 0.0050 - f2_score: 0.0242 - auc: 0.6353 - pr_auc: 0.0064

 52/222 [======>.......................] - ETA: 3s - loss: 1.8609 - recall: 0.6042 - precision: 0.0047 - f2_score: 0.0228 - auc: 0.6110 - pr_auc: 0.0059

 55/222 [======>.......................] - ETA: 3s - loss: 1.8721 - recall: 0.5800 - precision: 0.0044 - f2_score: 0.0216 - auc: 0.5960 - pr_auc: 0.0056

 58/222 [======>.......................] - ETA: 2s - loss: 1.8441 - recall: 0.5882 - precision: 0.0044 - f2_score: 0.0212 - auc: 0.6010 - pr_auc: 0.0054

 61/222 [=======>......................] - ETA: 2s - loss: 1.8720 - recall: 0.5893 - precision: 0.0046 - f2_score: 0.0222 - auc: 0.5999 - pr_auc: 0.0070

 64/222 [=======>......................] - ETA: 2s - loss: 1.8467 - recall: 0.6102 - precision: 0.0047 - f2_score: 0.0230 - auc: 0.6184 - pr_auc: 0.0078

 67/222 [========>.....................] - ETA: 2s - loss: 1.8509 - recall: 0.5902 - precision: 0.0045 - f2_score: 0.0220 - auc: 0.6097 - pr_auc: 0.0074

 70/222 [========>.....................] - ETA: 2s - loss: 1.8286 - recall: 0.5968 - precision: 0.0045 - f2_score: 0.0216 - auc: 0.6144 - pr_auc: 0.0072

 73/222 [========>.....................] - ETA: 2s - loss: 1.8258 - recall: 0.5781 - precision: 0.0043 - f2_score: 0.0208 - auc: 0.6100 - pr_auc: 0.0068

 76/222 [=========>....................] - ETA: 2s - loss: 1.8133 - recall: 0.5909 - precision: 0.0043 - f2_score: 0.0210 - auc: 0.6145 - pr_auc: 0.0067

 79/222 [=========>....................] - ETA: 2s - loss: 1.8314 - recall: 0.5714 - precision: 0.0043 - f2_score: 0.0207 - auc: 0.6072 - pr_auc: 0.0070

 82/222 [==========>...................] - ETA: 2s - loss: 1.8539 - recall: 0.5789 - precision: 0.0045 - f2_score: 0.0220 - auc: 0.6066 - pr_auc: 0.0076

 85/222 [==========>...................] - ETA: 2s - loss: 1.8388 - recall: 0.5844 - precision: 0.0045 - f2_score: 0.0217 - auc: 0.6074 - pr_auc: 0.0073

 88/222 [==========>...................] - ETA: 2s - loss: 1.8603 - recall: 0.5854 - precision: 0.0046 - f2_score: 0.0224 - auc: 0.6026 - pr_auc: 0.0071

 91/222 [===========>..................] - ETA: 2s - loss: 1.8712 - recall: 0.5882 - precision: 0.0047 - f2_score: 0.0226 - auc: 0.6008 - pr_auc: 0.0070

 94/222 [===========>..................] - ETA: 2s - loss: 1.8884 - recall: 0.5778 - precision: 0.0047 - f2_score: 0.0227 - auc: 0.5989 - pr_auc: 0.0074

 97/222 [============>.................] - ETA: 2s - loss: 1.8785 - recall: 0.5914 - precision: 0.0048 - f2_score: 0.0233 - auc: 0.6058 - pr_auc: 0.0074

100/222 [============>.................] - ETA: 2s - loss: 1.9141 - recall: 0.5816 - precision: 0.0048 - f2_score: 0.0234 - auc: 0.5964 - pr_auc: 0.0072

103/222 [============>.................] - ETA: 2s - loss: 1.9731 - recall: 0.5714 - precision: 0.0049 - f2_score: 0.0239 - auc: 0.5848 - pr_auc: 0.0081

106/222 [=============>................] - ETA: 2s - loss: 1.9610 - recall: 0.5701 - precision: 0.0049 - f2_score: 0.0236 - auc: 0.5871 - pr_auc: 0.0081

109/222 [=============>................] - ETA: 2s - loss: 1.9518 - recall: 0.5688 - precision: 0.0048 - f2_score: 0.0233 - auc: 0.5882 - pr_auc: 0.0081

112/222 [==============>...............] - ETA: 1s - loss: 1.9682 - recall: 0.5702 - precision: 0.0049 - f2_score: 0.0237 - auc: 0.5903 - pr_auc: 0.0097

115/222 [==============>...............] - ETA: 1s - loss: 1.9537 - recall: 0.5776 - precision: 0.0049 - f2_score: 0.0239 - auc: 0.5951 - pr_auc: 0.0097

118/222 [==============>...............] - ETA: 1s - loss: 1.9385 - recall: 0.5847 - precision: 0.0049 - f2_score: 0.0239 - auc: 0.6008 - pr_auc: 0.0096

121/222 [===============>..............] - ETA: 1s - loss: 1.9385 - recall: 0.5798 - precision: 0.0048 - f2_score: 0.0233 - auc: 0.5961 - pr_auc: 0.0094

124/222 [===============>..............] - ETA: 1s - loss: 1.9370 - recall: 0.5785 - precision: 0.0048 - f2_score: 0.0231 - auc: 0.5938 - pr_auc: 0.0092

127/222 [================>.............] - ETA: 1s - loss: 1.9373 - recall: 0.5840 - precision: 0.0049 - f2_score: 0.0235 - auc: 0.5963 - pr_auc: 0.0090

130/222 [================>.............] - ETA: 1s - loss: 1.9409 - recall: 0.5703 - precision: 0.0047 - f2_score: 0.0230 - auc: 0.5923 - pr_auc: 0.0088

133/222 [================>.............] - ETA: 1s - loss: 1.9312 - recall: 0.5802 - precision: 0.0048 - f2_score: 0.0234 - auc: 0.5975 - pr_auc: 0.0098

136/222 [=================>............] - ETA: 1s - loss: 1.9228 - recall: 0.5896 - precision: 0.0049 - f2_score: 0.0238 - auc: 0.6023 - pr_auc: 0.0099

139/222 [=================>............] - ETA: 1s - loss: 1.9278 - recall: 0.5971 - precision: 0.0051 - f2_score: 0.0245 - auc: 0.6035 - pr_auc: 0.0097

142/222 [==================>...........] - ETA: 1s - loss: 1.9130 - recall: 0.5971 - precision: 0.0049 - f2_score: 0.0239 - auc: 0.6035 - pr_auc: 0.0096

145/222 [==================>...........] - ETA: 1s - loss: 1.9145 - recall: 0.6042 - precision: 0.0051 - f2_score: 0.0246 - auc: 0.6073 - pr_auc: 0.0106

148/222 [===================>..........] - ETA: 1s - loss: 1.9245 - recall: 0.5946 - precision: 0.0050 - f2_score: 0.0244 - auc: 0.6035 - pr_auc: 0.0103

151/222 [===================>..........] - ETA: 1s - loss: 1.9142 - recall: 0.6000 - precision: 0.0050 - f2_score: 0.0244 - auc: 0.6073 - pr_auc: 0.0103

154/222 [===================>..........] - ETA: 1s - loss: 1.9133 - recall: 0.6013 - precision: 0.0051 - f2_score: 0.0245 - auc: 0.6084 - pr_auc: 0.0102

157/222 [====================>.........] - ETA: 1s - loss: 1.9058 - recall: 0.5974 - precision: 0.0050 - f2_score: 0.0240 - auc: 0.6071 - pr_auc: 0.0100

160/222 [====================>.........] - ETA: 1s - loss: 1.9161 - recall: 0.5924 - precision: 0.0049 - f2_score: 0.0239 - auc: 0.6027 - pr_auc: 0.0100

163/222 [=====================>........] - ETA: 1s - loss: 1.9170 - recall: 0.5912 - precision: 0.0049 - f2_score: 0.0237 - auc: 0.6003 - pr_auc: 0.0097

166/222 [=====================>........] - ETA: 0s - loss: 1.9167 - recall: 0.5864 - precision: 0.0049 - f2_score: 0.0235 - auc: 0.5995 - pr_auc: 0.0095

169/222 [=====================>........] - ETA: 0s - loss: 1.9104 - recall: 0.5879 - precision: 0.0049 - f2_score: 0.0236 - auc: 0.6030 - pr_auc: 0.0105

172/222 [======================>.......] - ETA: 0s - loss: 1.9066 - recall: 0.5952 - precision: 0.0049 - f2_score: 0.0238 - auc: 0.6052 - pr_auc: 0.0103

175/222 [======================>.......] - ETA: 0s - loss: 1.9158 - recall: 0.5872 - precision: 0.0049 - f2_score: 0.0237 - auc: 0.6013 - pr_auc: 0.0099

178/222 [=======================>......] - ETA: 0s - loss: 1.9318 - recall: 0.5829 - precision: 0.0049 - f2_score: 0.0235 - auc: 0.5979 - pr_auc: 0.0107

181/222 [=======================>......] - ETA: 0s - loss: 1.9346 - recall: 0.5866 - precision: 0.0049 - f2_score: 0.0238 - auc: 0.5996 - pr_auc: 0.0106

184/222 [=======================>......] - ETA: 0s - loss: 1.9364 - recall: 0.5902 - precision: 0.0050 - f2_score: 0.0241 - auc: 0.6002 - pr_auc: 0.0105

187/222 [========================>.....] - ETA: 0s - loss: 1.9456 - recall: 0.5914 - precision: 0.0050 - f2_score: 0.0241 - auc: 0.5975 - pr_auc: 0.0103

190/222 [========================>.....] - ETA: 0s - loss: 1.9360 - recall: 0.5979 - precision: 0.0050 - f2_score: 0.0244 - auc: 0.6033 - pr_auc: 0.0106

193/222 [=========================>....] - ETA: 0s - loss: 1.9257 - recall: 0.6042 - precision: 0.0051 - f2_score: 0.0246 - auc: 0.6093 - pr_auc: 0.0117

196/222 [=========================>....] - ETA: 0s - loss: 1.9357 - recall: 0.5969 - precision: 0.0051 - f2_score: 0.0245 - auc: 0.6051 - pr_auc: 0.0115

199/222 [=========================>....] - ETA: 0s - loss: 1.9365 - recall: 0.6000 - precision: 0.0051 - f2_score: 0.0247 - auc: 0.6070 - pr_auc: 0.0115

202/222 [==========================>...] - ETA: 0s - loss: 1.9457 - recall: 0.5971 - precision: 0.0052 - f2_score: 0.0249 - auc: 0.6061 - pr_auc: 0.0113

205/222 [==========================>...] - ETA: 0s - loss: 1.9368 - recall: 0.6010 - precision: 0.0052 - f2_score: 0.0250 - auc: 0.6094 - pr_auc: 0.0112

208/222 [===========================>..] - ETA: 0s - loss: 1.9265 - recall: 0.6010 - precision: 0.0051 - f2_score: 0.0247 - auc: 0.6095 - pr_auc: 0.0110

211/222 [===========================>..] - ETA: 0s - loss: 1.9166 - recall: 0.6010 - precision: 0.0050 - f2_score: 0.0243 - auc: 0.6095 - pr_auc: 0.0109

214/222 [===========================>..] - ETA: 0s - loss: 1.9183 - recall: 0.6019 - precision: 0.0050 - f2_score: 0.0244 - auc: 0.6079 - pr_auc: 0.0107

217/222 [============================>.] - ETA: 0s - loss: 1.9215 - recall: 0.5972 - precision: 0.0051 - f2_score: 0.0244 - auc: 0.6086 - pr_auc: 0.0108

220/222 [============================>.] - ETA: 0s - loss: 1.9157 - recall: 0.6027 - precision: 0.0051 - f2_score: 0.0247 - auc: 0.6118 - pr_auc: 0.0115

  [F2GridMonitor] val_f2_grid_max=0.1061 @ th=0.78
222/222 [==============================] - 6s 29ms/step - loss: 1.9186 - recall: 0.6036 - precision: 0.0052 - f2_score: 0.0249 - auc: 0.6126 - pr_auc: 0.0119 - val_loss: 1.6832 - val_recall: 0.5106 - val_precision: 0.0077 - val_f2_score: 0.0361 - val_auc: 0.7033 - val_pr_auc: 0.0136 - val_f2_grid_max: 0.1061 - val_f2_best_th: 0.7800 - lr: 1.0000e-04

Epoch 4/50

  1/222 [..............................] - ETA: 4s - loss: 2.3337 - recall: 0.0000e+00 - precision: 0.0000e+00 - f2_score: 0.0000e+00 - auc: 0.3353 - pr_auc: 0.0029

  4/222 [..............................] - ETA: 3s - loss: 1.9000 - recall: 0.5000 - precision: 0.0043 - f2_score: 0.0209 - auc: 0.5868 - pr_auc: 0.0050

  7/222 [..............................] - ETA: 3s - loss: 1.7949 - recall: 0.5000 - precision: 0.0036 - f2_score: 0.0177 - auc: 0.5930 - pr_auc: 0.0105

 10/222 [>.............................] - ETA: 3s - loss: 2.0707 - recall: 0.4545 - precision: 0.0042 - f2_score: 0.0204 - auc: 0.5635 - pr_auc: 0.0084

 13/222 [>.............................] - ETA: 3s - loss: 2.2024 - recall: 0.5789 - precision: 0.0073 - f2_score: 0.0346 - auc: 0.6193 - pr_auc: 0.0137

 16/222 [=>............................] - ETA: 3s - loss: 2.1602 - recall: 0.5238 - precision: 0.0058 - f2_score: 0.0280 - auc: 0.5906 - pr_auc: 0.0107

 19/222 [=>............................] - ETA: 3s - loss: 2.0595 - recall: 0.5417 - precision: 0.0058 - f2_score: 0.0279 - auc: 0.6186 - pr_auc: 0.0161

 22/222 [=>............................] - ETA: 3s - loss: 1.9436 - recall: 0.5417 - precision: 0.0050 - f2_score: 0.0242 - auc: 0.6203 - pr_auc: 0.0141

 25/222 [==>...........................] - ETA: 3s - loss: 1.9928 - recall: 0.5357 - precision: 0.0051 - f2_score: 0.0248 - auc: 0.6146 - pr_auc: 0.0122

 28/222 [==>...........................] - ETA: 3s - loss: 2.0009 - recall: 0.5161 - precision: 0.0049 - f2_score: 0.0236 - auc: 0.5993 - pr_auc: 0.0106

 31/222 [===>..........................] - ETA: 3s - loss: 1.9555 - recall: 0.5455 - precision: 0.0050 - f2_score: 0.0240 - auc: 0.6059 - pr_auc: 0.0099

 34/222 [===>..........................] - ETA: 3s - loss: 1.8909 - recall: 0.5588 - precision: 0.0048 - f2_score: 0.0231 - auc: 0.6175 - pr_auc: 0.0104

 37/222 [====>.........................] - ETA: 3s - loss: 1.8385 - recall: 0.5588 - precision: 0.0044 - f2_score: 0.0213 - auc: 0.6170 - pr_auc: 0.0096

 40/222 [====>.........................] - ETA: 3s - loss: 1.8458 - recall: 0.6154 - precision: 0.0052 - f2_score: 0.0250 - auc: 0.6326 - pr_auc: 0.0094

 43/222 [====>.........................] - ETA: 3s - loss: 1.8291 - recall: 0.6429 - precision: 0.0054 - f2_score: 0.0261 - auc: 0.6411 - pr_auc: 0.0104

 46/222 [=====>........................] - ETA: 3s - loss: 1.8578 - recall: 0.6304 - precision: 0.0054 - f2_score: 0.0262 - auc: 0.6309 - pr_auc: 0.0097

 49/222 [=====>........................] - ETA: 3s - loss: 1.9040 - recall: 0.6042 - precision: 0.0051 - f2_score: 0.0246 - auc: 0.6073 - pr_auc: 0.0089

 52/222 [======>.......................] - ETA: 3s - loss: 1.9486 - recall: 0.5686 - precision: 0.0048 - f2_score: 0.0232 - auc: 0.5900 - pr_auc: 0.0082

 55/222 [======>.......................] - ETA: 3s - loss: 1.9192 - recall: 0.5769 - precision: 0.0047 - f2_score: 0.0227 - auc: 0.5908 - pr_auc: 0.0078

 58/222 [======>.......................] - ETA: 3s - loss: 1.9045 - recall: 0.5818 - precision: 0.0047 - f2_score: 0.0230 - auc: 0.5993 - pr_auc: 0.0081

 61/222 [=======>......................] - ETA: 3s - loss: 1.8835 - recall: 0.5714 - precision: 0.0045 - f2_score: 0.0219 - auc: 0.5973 - pr_auc: 0.0077

 64/222 [=======>......................] - ETA: 2s - loss: 1.8603 - recall: 0.5862 - precision: 0.0046 - f2_score: 0.0222 - auc: 0.6053 - pr_auc: 0.0082

 67/222 [========>.....................] - ETA: 2s - loss: 1.8489 - recall: 0.6066 - precision: 0.0047 - f2_score: 0.0230 - auc: 0.6123 - pr_auc: 0.0100

 70/222 [========>.....................] - ETA: 2s - loss: 1.8682 - recall: 0.5846 - precision: 0.0047 - f2_score: 0.0226 - auc: 0.6040 - pr_auc: 0.0094

 73/222 [========>.....................] - ETA: 2s - loss: 1.8743 - recall: 0.5942 - precision: 0.0048 - f2_score: 0.0234 - auc: 0.6089 - pr_auc: 0.0108

 76/222 [=========>....................] - ETA: 2s - loss: 1.8693 - recall: 0.6027 - precision: 0.0050 - f2_score: 0.0241 - auc: 0.6172 - pr_auc: 0.0142

 79/222 [=========>....................] - ETA: 2s - loss: 1.8475 - recall: 0.6081 - precision: 0.0049 - f2_score: 0.0237 - auc: 0.6211 - pr_auc: 0.0139

 82/222 [==========>...................] - ETA: 2s - loss: 1.8282 - recall: 0.6184 - precision: 0.0049 - f2_score: 0.0239 - auc: 0.6297 - pr_auc: 0.0135

 85/222 [==========>...................] - ETA: 2s - loss: 1.8252 - recall: 0.6203 - precision: 0.0049 - f2_score: 0.0240 - auc: 0.6318 - pr_auc: 0.0132

 88/222 [==========>...................] - ETA: 2s - loss: 1.8354 - recall: 0.6190 - precision: 0.0051 - f2_score: 0.0246 - auc: 0.6336 - pr_auc: 0.0153

 91/222 [===========>..................] - ETA: 2s - loss: 1.8209 - recall: 0.6279 - precision: 0.0051 - f2_score: 0.0247 - auc: 0.6391 - pr_auc: 0.0150

 94/222 [===========>..................] - ETA: 2s - loss: 1.8162 - recall: 0.6292 - precision: 0.0051 - f2_score: 0.0248 - auc: 0.6417 - pr_auc: 0.0145

 97/222 [============>.................] - ETA: 2s - loss: 1.8321 - recall: 0.6383 - precision: 0.0053 - f2_score: 0.0258 - auc: 0.6401 - pr_auc: 0.0139

100/222 [============>.................] - ETA: 2s - loss: 1.8425 - recall: 0.6364 - precision: 0.0054 - f2_score: 0.0262 - auc: 0.6392 - pr_auc: 0.0146

103/222 [============>.................] - ETA: 2s - loss: 1.8573 - recall: 0.6346 - precision: 0.0055 - f2_score: 0.0267 - auc: 0.6362 - pr_auc: 0.0142

106/222 [=============>................] - ETA: 2s - loss: 1.8681 - recall: 0.6355 - precision: 0.0056 - f2_score: 0.0268 - auc: 0.6327 - pr_auc: 0.0135

109/222 [=============>................] - ETA: 2s - loss: 1.8751 - recall: 0.6273 - precision: 0.0055 - f2_score: 0.0265 - auc: 0.6282 - pr_auc: 0.0132

112/222 [==============>...............] - ETA: 2s - loss: 1.8677 - recall: 0.6250 - precision: 0.0054 - f2_score: 0.0261 - auc: 0.6284 - pr_auc: 0.0133

115/222 [==============>...............] - ETA: 1s - loss: 1.8788 - recall: 0.6207 - precision: 0.0054 - f2_score: 0.0261 - auc: 0.6245 - pr_auc: 0.0128

118/222 [==============>...............] - ETA: 1s - loss: 1.8667 - recall: 0.6271 - precision: 0.0054 - f2_score: 0.0262 - auc: 0.6287 - pr_auc: 0.0126

121/222 [===============>..............] - ETA: 1s - loss: 1.8557 - recall: 0.6364 - precision: 0.0055 - f2_score: 0.0266 - auc: 0.6350 - pr_auc: 0.0136

124/222 [===============>..............] - ETA: 1s - loss: 1.8620 - recall: 0.6371 - precision: 0.0055 - f2_score: 0.0266 - auc: 0.6301 - pr_auc: 0.0133

127/222 [================>.............] - ETA: 1s - loss: 1.8613 - recall: 0.6406 - precision: 0.0056 - f2_score: 0.0270 - auc: 0.6330 - pr_auc: 0.0129

130/222 [================>.............] - ETA: 1s - loss: 1.8707 - recall: 0.6391 - precision: 0.0057 - f2_score: 0.0273 - auc: 0.6328 - pr_auc: 0.0128

133/222 [================>.............] - ETA: 1s - loss: 1.8569 - recall: 0.6418 - precision: 0.0056 - f2_score: 0.0270 - auc: 0.6352 - pr_auc: 0.0126

136/222 [=================>............] - ETA: 1s - loss: 1.8576 - recall: 0.6350 - precision: 0.0055 - f2_score: 0.0267 - auc: 0.6336 - pr_auc: 0.0122

139/222 [=================>............] - ETA: 1s - loss: 1.8462 - recall: 0.6377 - precision: 0.0055 - f2_score: 0.0265 - auc: 0.6348 - pr_auc: 0.0120

142/222 [==================>...........] - ETA: 1s - loss: 1.8442 - recall: 0.6383 - precision: 0.0055 - f2_score: 0.0265 - auc: 0.6353 - pr_auc: 0.0117

145/222 [==================>...........] - ETA: 1s - loss: 1.8452 - recall: 0.6414 - precision: 0.0056 - f2_score: 0.0269 - auc: 0.6364 - pr_auc: 0.0117

148/222 [===================>..........] - ETA: 1s - loss: 1.8443 - recall: 0.6327 - precision: 0.0055 - f2_score: 0.0264 - auc: 0.6333 - pr_auc: 0.0114

151/222 [===================>..........] - ETA: 1s - loss: 1.8354 - recall: 0.6376 - precision: 0.0055 - f2_score: 0.0264 - auc: 0.6362 - pr_auc: 0.0113

154/222 [===================>..........] - ETA: 1s - loss: 1.8249 - recall: 0.6400 - precision: 0.0054 - f2_score: 0.0262 - auc: 0.6377 - pr_auc: 0.0112

157/222 [====================>.........] - ETA: 1s - loss: 1.8199 - recall: 0.6382 - precision: 0.0054 - f2_score: 0.0259 - auc: 0.6381 - pr_auc: 0.0110

160/222 [====================>.........] - ETA: 1s - loss: 1.8168 - recall: 0.6340 - precision: 0.0053 - f2_score: 0.0255 - auc: 0.6352 - pr_auc: 0.0108

163/222 [=====================>........] - ETA: 1s - loss: 1.8066 - recall: 0.6387 - precision: 0.0053 - f2_score: 0.0255 - auc: 0.6393 - pr_auc: 0.0114

166/222 [=====================>........] - ETA: 1s - loss: 1.8133 - recall: 0.6289 - precision: 0.0052 - f2_score: 0.0253 - auc: 0.6363 - pr_auc: 0.0111

169/222 [=====================>........] - ETA: 0s - loss: 1.8226 - recall: 0.6258 - precision: 0.0053 - f2_score: 0.0254 - auc: 0.6317 - pr_auc: 0.0108

172/222 [======================>.......] - ETA: 0s - loss: 1.8232 - recall: 0.6265 - precision: 0.0053 - f2_score: 0.0255 - auc: 0.6311 - pr_auc: 0.0106

175/222 [======================>.......] - ETA: 0s - loss: 1.8212 - recall: 0.6228 - precision: 0.0052 - f2_score: 0.0250 - auc: 0.6280 - pr_auc: 0.0104

178/222 [=======================>......] - ETA: 0s - loss: 1.8173 - recall: 0.6213 - precision: 0.0051 - f2_score: 0.0248 - auc: 0.6281 - pr_auc: 0.0102

181/222 [=======================>......] - ETA: 0s - loss: 1.8254 - recall: 0.6207 - precision: 0.0052 - f2_score: 0.0251 - auc: 0.6287 - pr_auc: 0.0102

184/222 [=======================>......] - ETA: 0s - loss: 1.8180 - recall: 0.6271 - precision: 0.0052 - f2_score: 0.0254 - auc: 0.6335 - pr_auc: 0.0113

187/222 [========================>.....] - ETA: 0s - loss: 1.8238 - recall: 0.6188 - precision: 0.0052 - f2_score: 0.0252 - auc: 0.6312 - pr_auc: 0.0111

190/222 [========================>.....] - ETA: 0s - loss: 1.8206 - recall: 0.6196 - precision: 0.0052 - f2_score: 0.0253 - auc: 0.6332 - pr_auc: 0.0114

193/222 [=========================>....] - ETA: 0s - loss: 1.8186 - recall: 0.6183 - precision: 0.0052 - f2_score: 0.0251 - auc: 0.6321 - pr_auc: 0.0112

196/222 [=========================>....] - ETA: 0s - loss: 1.8186 - recall: 0.6211 - precision: 0.0052 - f2_score: 0.0253 - auc: 0.6338 - pr_auc: 0.0112

199/222 [=========================>....] - ETA: 0s - loss: 1.8332 - recall: 0.6154 - precision: 0.0052 - f2_score: 0.0254 - auc: 0.6286 - pr_auc: 0.0110

202/222 [==========================>...] - ETA: 0s - loss: 1.8253 - recall: 0.6193 - precision: 0.0053 - f2_score: 0.0254 - auc: 0.6319 - pr_auc: 0.0110

205/222 [==========================>...] - ETA: 0s - loss: 1.8332 - recall: 0.6238 - precision: 0.0054 - f2_score: 0.0259 - auc: 0.6322 - pr_auc: 0.0109

208/222 [===========================>..] - ETA: 0s - loss: 1.8417 - recall: 0.6262 - precision: 0.0054 - f2_score: 0.0261 - auc: 0.6324 - pr_auc: 0.0108

211/222 [===========================>..] - ETA: 0s - loss: 1.8569 - recall: 0.6226 - precision: 0.0054 - f2_score: 0.0263 - auc: 0.6278 - pr_auc: 0.0106

214/222 [===========================>..] - ETA: 0s - loss: 1.8579 - recall: 0.6250 - precision: 0.0055 - f2_score: 0.0266 - auc: 0.6283 - pr_auc: 0.0113

217/222 [============================>.] - ETA: 0s - loss: 1.8506 - recall: 0.6267 - precision: 0.0055 - f2_score: 0.0264 - auc: 0.6289 - pr_auc: 0.0111

220/222 [============================>.] - ETA: 0s - loss: 1.8610 - recall: 0.6199 - precision: 0.0054 - f2_score: 0.0262 - auc: 0.6251 - pr_auc: 0.0109

  [F2GridMonitor] val_f2_grid_max=0.1176 @ th=0.73
222/222 [==============================] - 7s 29ms/step - loss: 1.8592 - recall: 0.6216 - precision: 0.0054 - f2_score: 0.0263 - auc: 0.6260 - pr_auc: 0.0109 - val_loss: 1.6264 - val_recall: 0.5745 - val_precision: 0.0098 - val_f2_score: 0.0457 - val_auc: 0.7576 - val_pr_auc: 0.0167 - val_f2_grid_max: 0.1176 - val_f2_best_th: 0.7300 - lr: 1.0000e-04

Epoch 5/50

  1/222 [..............................] - ETA: 4s - loss: 2.4366 - recall: 0.6667 - precision: 0.0190 - f2_score: 0.0855 - auc: 0.7708 - pr_auc: 0.0388

  4/222 [..............................] - ETA: 3s - loss: 2.2534 - recall: 0.5000 - precision: 0.0085 - f2_score: 0.0396 - auc: 0.6750 - pr_auc: 0.0246

  7/222 [..............................] - ETA: 3s - loss: 1.8438 - recall: 0.5556 - precision: 0.0061 - f2_score: 0.0293 - auc: 0.6935 - pr_auc: 0.0153

 10/222 [>.............................] - ETA: 3s - loss: 2.1037 - recall: 0.5333 - precision: 0.0069 - f2_score: 0.0327 - auc: 0.6303 - pr_auc: 0.0102

 13/222 [>.............................] - ETA: 3s - loss: 2.0935 - recall: 0.5294 - precision: 0.0060 - f2_score: 0.0289 - auc: 0.6157 - pr_auc: 0.0103

 16/222 [=>............................] - ETA: 3s - loss: 1.9649 - recall: 0.5556 - precision: 0.0055 - f2_score: 0.0265 - auc: 0.6147 - pr_auc: 0.0085

 19/222 [=>............................] - ETA: 3s - loss: 1.9277 - recall: 0.5909 - precision: 0.0060 - f2_score: 0.0290 - auc: 0.6439 - pr_auc: 0.0092

 22/222 [=>............................] - ETA: 3s - loss: 1.8518 - recall: 0.6400 - precision: 0.0064 - f2_score: 0.0308 - auc: 0.6772 - pr_auc: 0.0116

 25/222 [==>...........................] - ETA: 3s - loss: 1.9068 - recall: 0.6452 - precision: 0.0070 - f2_score: 0.0337 - auc: 0.6748 - pr_auc: 0.0209

 28/222 [==>...........................] - ETA: 3s - loss: 1.9330 - recall: 0.6471 - precision: 0.0069 - f2_score: 0.0331 - auc: 0.6645 - pr_auc: 0.0235

 31/222 [===>..........................] - ETA: 3s - loss: 1.9097 - recall: 0.6389 - precision: 0.0065 - f2_score: 0.0311 - auc: 0.6576 - pr_auc: 0.0212

 34/222 [===>..........................] - ETA: 3s - loss: 1.8470 - recall: 0.6486 - precision: 0.0062 - f2_score: 0.0298 - auc: 0.6672 - pr_auc: 0.0226

 37/222 [====>.........................] - ETA: 3s - loss: 1.8133 - recall: 0.6316 - precision: 0.0057 - f2_score: 0.0275 - auc: 0.6633 - pr_auc: 0.0199

 40/222 [====>.........................] - ETA: 3s - loss: 1.7862 - recall: 0.6500 - precision: 0.0057 - f2_score: 0.0276 - auc: 0.6700 - pr_auc: 0.0180

 43/222 [====>.........................] - ETA: 3s - loss: 1.7571 - recall: 0.6585 - precision: 0.0055 - f2_score: 0.0266 - auc: 0.6699 - pr_auc: 0.0171

 46/222 [=====>........................] - ETA: 3s - loss: 1.7866 - recall: 0.6522 - precision: 0.0057 - f2_score: 0.0277 - auc: 0.6678 - pr_auc: 0.0155

 49/222 [=====>........................] - ETA: 3s - loss: 1.7669 - recall: 0.6383 - precision: 0.0054 - f2_score: 0.0261 - auc: 0.6630 - pr_auc: 0.0143

Training in progress...